alpaca_predict.py --input_file none --output_file none
alpaca_predict.py --input_file none --output_file none
alpaca_predict.py --input_file none --output_file none
alpaca_predict.py --input_file none --output_file none
alpaca_predict.py --input_file none --output_file none
alpaca_predict.py --input_file none --output_file none
alpaca_predict.py --input_file none --output_file none
alpaca_predict.py --input_file none --output_file none
alpaca_predict.py --input_file none --output_file none
alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_file experiments/prediction_files/conll/alpaca.pred
alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_file experiments/prediction_files/conll/alpaca.pred
alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_file experiments/prediction_files/conll/alpaca.pred
alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_file experiments/prediction_files/conll/alpaca.pred
alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_file experiments/prediction_files/conll/alpaca.pred
alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_file experiments/prediction_files/conll/alpaca.pred --force_cpu
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 2 --batch_ind 4
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 2 --batch_ind 4
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 2 --batch_ind 4
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 4 --batch_ind 4
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 24
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 88
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 99
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 76
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 58
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 36
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 81
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 13
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 65
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 92
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 47
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 42
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 31
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 70
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 20
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 54
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 37
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 82
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 78
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 71
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 15//home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 60//home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 49//home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 62
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 28
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 3
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 87
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 69
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 96
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 19
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 64
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 75
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 1
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 79
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 11
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 30
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 67
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 8
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 52
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 22
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 86
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 90
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 98
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 41
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 18
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 56
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 45
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 33
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 17
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 46
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 51
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 12
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 63
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 85
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 2
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 40
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 91
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 7
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 74
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 97
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 23
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 68
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 57
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 80
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 29
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 34
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 66
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 27
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 16
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 61
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 32
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 50
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 89
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 6
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 21
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 100
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 9
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 84
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 39
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 43
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 77
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 95
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 73
/home/alta/BLTSpeaking/exp-vr313/GEC/mbr_gec/alpaca_predict.py --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_dir experiments/prediction_files/conll/alpaca --force_cpu --batch --batch_size 15 --batch_ind 55
