pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/pr_data/confidence/Linguaskill_ft/ensemble.pkl --target_file ../data/Linguaskill/preprocessed/ls_test.corr --transformer_model xlnet --special_tokens_fix 0 --model_name ensemble_speech_ft --is_ensemble 1 --speech 1
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/pr_data/confidence/Linguaskill_ft/ensemble.pkl --target_file ../data/Linguaskill/preprocessed/ls_test.corr --transformer_model xlnet --special_tokens_fix 0 --model_name ensemble_speech_ft --is_ensemble 1 --speech 1
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/pr_data/confidence/Linguaskill_ft/ensemble.pkl --target_file ../data/Linguaskill/preprocessed/ls_test.corr --transformer_model xlnet --special_tokens_fix 0 --model_name ensemble_speech_ft --is_ensemble 1 --speech 1
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th--vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/pr_data/confidence/Linguaskill_combi/ensemble.pkl --target_file ../data/Linguaskill/preprocessed/ls_test.corr --transformer_model xlnet --special_tokens_fix 0 --model_name ensemble_speech_ft --is_ensemble 1 --speech 1
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/pr_data/confidence/Linguaskill_combi/ensemble.pkl --target_file ../data/Linguaskill/preprocessed/ls_test.corr --transformer_model xlnet --special_tokens_fix 0 --model_name ensemble_speech_combi --is_ensemble 1 --speech 1
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/pr_data/confidence/Linguaskill/ensemble.pkl --target_file ../data/Linguaskill/preprocessed/ls_test.corr --transformer_model xlnet --special_tokens_fix 0 --model_name ensemble_speech_no_ft --is_ensemble 1 --speech 1pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/pr_data/confidence/Linguaskill/ensemble.pkl --target_file ../data/Linguaskill/preprocessed/ls_test.corr --transformer_model xlnet --special_tokens_fix 0 --model_name ensemble_speech_no_ft --is_ensemble 1 --speech 1
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/pr_data/confidence/Linguaskill_combi/ensemble.pkl --target_file ../data/Linguaskill/preprocessed/ls_test.corr --transformer_model xlnet --special_tokens_fix 0 --model_name ensemble_speech_combi --is_ensemble 1 --speech 1
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test_reduced.inc --output_file experiments/pr_data/confidence/Linguaskill_combi/ensemble_reduced.pkl --target_file ../data/Linguaskill/preprocessed/ls_test_reduced.corr --transformer_model xlnet --special_tokens_fix 0 --model_name ensemble_speech_combi --is_ensemble 1 --speech 1 --n_steps 5

pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test_reduced.inc --output_file experiments/pr_data/confidence/Linguaskill_combi/ensemble_reduced.pkl --target_file ../data/Linguaskill/preprocessed/ls_test_reduced.corr --transformer_model xlnet --special_tokens_fix 0 --model_name ensemble_speech_combi --is_ensemble 1 --speech 1 --n_steps 5
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test_reduced.inc --output_file experiments/pr_data/confidence/Linguaskill_combi/ensemble_reduced.pkl --target_file ../data/Linguaskill/preprocessed/ls_test_reduced.corr --transformer_model xlnet --special_tokens_fix 0 --model_name ensemble_speech_combi --is_ensemble 1 --speech 1 --n_steps 2
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test_reduced.inc --output_file experiments/pr_data/confidence/Linguaskill_combi/ensemble_reduced.pkl --target_file ../data/Linguaskill/preprocessed/ls_test_reduced.corr --transformer_model xlnet --special_tokens_fix 0 --model_name ensemble_speech_combi --is_ensemble 1 --speech 1 --n_steps 2
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test_reduced.inc --output_file experiments/pr_data/confidence/Linguaskill_combi/ensemble_reduced.pkl --target_file ../data/Linguaskill/preprocessed/ls_test_reduced.corr --transformer_model xlnet --special_tokens_fix 0 --model_name ensemble_speech_combi --is_ensemble 1 --speech 1 --n_steps 2
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test_reduced.inc --output_file experiments/pr_data/confidence/Linguaskill_combi/ensemble_reduced.pkl --target_file ../data/Linguaskill/preprocessed/ls_test_reduced.corr --transformer_model xlnet --special_tokens_fix 0 --model_name ensemble_speech_combi --is_ensemble 1 --speech 1 --n_steps 2
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/pr_data/confidence/Linguaskill_combi/ensemble.pkl --target_file ../data/Linguaskill/preprocessed/ls_test.corr --transformer_model xlnet --special_tokens_fix 0 --model_name ensemble_speech_combi --is_ensemble 1 --speech 1
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed_whisperflt/ls_test.inc --output_file experiments/pr_data/confidence/Linguaskill_ft/ensemble.pkl --target_file ../data/Linguaskill/preprocessed/ls_test.corr --transformer_model xlnet --special_tokens_fix 0 --model_name ensemble_speech_ft --is_ensemble 1 --speech 1
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/pr_data/confidence/Linguaskill/ensemble.pkl --target_file ../data/Linguaskill/preprocessed/ls_test.corr --transformer_model xlnet --special_tokens_fix 0 --model_name ensemble_speech_no_ft --is_ensemble 1 --speech 1

pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --output_file experiments/pr_data/confidence/Linguaskill_whisperflt/ensemble_all.pkl --is_ensemble 1 --speech 1 --model_name ensemble_all_whisper --special_tokens_fix 0
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --output_file experiments/pr_data/confidence/Linguaskill_whisperflt/ensemble_all.pkl --is_ensemble 1 --speech 1 --model_name ensemble_all_whisper --special_tokens_fix 0
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --output_file experiments/pr_data/confidence/Linguaskill_whisperflt/ensemble_ft.pkl --is_ensemble 1 --speech 1 --model_name ensemble_all_whisper --special_tokens_fix 0
/scratches/dialfs/alta/th624/exp-th624/Calibration_Uncertainty_GEC/pr_confidence.py
/scratches/dialfs/alta/th624/exp-th624/Calibration_Uncertainty_GEC/pr_confidence.py
/scratches/dialfs/alta/th624/exp-th624/Calibration_Uncertainty_GEC/pr_confidence.py
/scratches/dialfs/alta/th624/exp-th624/Calibration_Uncertainty_GEC/pr_confidence.py
/scratches/dialfs/alta/th624/exp-th624/Calibration_Uncertainty_GEC/pr_confidence.py
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --output_file experiments/pr_data/confidence/Linguaskill_whisperflt/ensemble_ft.pkl --is_ensemble 1 --speech 1 --model_name ensemble_all_whisper --special_tokens_fix 0
/scratches/dialfs/alta/th624/exp-th624/Calibration_Uncertainty_GEC/pr_confidence.py
/scratches/dialfs/alta/th624/exp-th624/Calibration_Uncertainty_GEC/pr_confidence.py
/scratches/dialfs/alta/th624/exp-th624/Calibration_Uncertainty_GEC/pr_confidence.py
/scratches/dialfs/alta/th624/exp-th624/Calibration_Uncertainty_GEC/pr_confidence.py
/scratches/dialfs/alta/th624/exp-th624/Calibration_Uncertainty_GEC/pr_confidence.py
/scratches/dialfs/alta/th624/exp-th624/Calibration_Uncertainty_GEC/pr_confidence.py
/scratches/dialfs/alta/th624/exp-th624/Calibration_Uncertainty_GEC/pr_confidence.py
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --output_file experiments/pr_data/confidence/Linguaskill_whisperflt/ensemble_all_asr_only_gec0.pkl --is_ensemble 1 --speech 1 --model_name ensemble_all1 --special_tokens_fix 0 --spoken_gec_threshold_mode asr_only
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --output_file experiments/pr_data/confidence/Linguaskill_whisperflt/ensemble_all_prod_1_1.pkl --is_ensemble 1 --speech 1 --model_name ensemble_all4 --special_tokens_fix 0 --spoken_gec_threshold_mode weighted_product --alpha 1 --beta 1
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --output_file experiments/pr_data/confidence/Linguaskill_whisperflt/ensemble_all_prod_2_1.pkl --is_ensemble 1 --speech 1 --model_name ensemble_all5 --special_tokens_fix 0 --spoken_gec_threshold_mode weighted_product --alpha 2 --beta 1
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --output_file experiments/pr_data/confidence/Linguaskill_whisperflt/ensemble_all_gec_only_asr0.75.pkl --is_ensemble 1 --speech 1 --model_name ensemble_all2 --special_tokens_fix 0 --threshold_constant 0.75 --spoken_gec_threshold_mode gec_only
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --output_file experiments/pr_data/confidence/Linguaskill_whisperflt/ensemble_all_prod_1_1.pkl --is_ensemble 1 --speech 1 --model_name ensemble_all4 --special_tokens_fix 0 --spoken_gec_threshold_mode weighted_product --alpha 1 --beta 1
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --output_file experiments/pr_data/confidence/Linguaskill_whisperflt/ensemble_all_gec_only_asr0.75.pkl --is_ensemble 1 --speech 1 --model_name ensemble_all2 --special_tokens_fix 0 --threshold_constant 0.75 --spoken_gec_threshold_mode gec_only
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --output_file experiments/pr_data/confidence/Linguaskill_whisperflt/ensemble_all_prod_2_1.pkl --is_ensemble 1 --speech 1 --model_name ensemble_all5 --special_tokens_fix 0 --spoken_gec_threshold_mode weighted_product --alpha 2 --beta 1
/scratches/dialfs/alta/th624/exp-th624/Calibration_Uncertainty_GEC/pr_confidence.py
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --output_file experiments/pr_data/confidence/Linguaskill_whisperflt/ensemble_all_gec_only_asr0.75.pkl --is_ensemble 1 --speech 1 --model_name ensemble_all2 --special_tokens_fix 0 --threshold_constant 0.75 --spoken_gec_threshold_mode gec_only
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --output_file experiments/pr_data/confidence/Linguaskill_whisperflt/ensemble_all_prod_1_1.pkl --is_ensemble 1 --speech 1 --model_name ensemble_all4 --special_tokens_fix 0 --spoken_gec_threshold_mode weighted_product --alpha 1 --beta 1
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --output_file experiments/pr_data/confidence/Linguaskill_whisperflt/ensemble_all_prod_1_1.pkl --is_ensemble 1 --speech 1 --model_name ensemble_all4 --special_tokens_fix 0 --spoken_gec_threshold_mode weighted_product --alpha 1 --beta 1
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --output_file experiments/pr_data/confidence/Linguaskill_whisperflt/ensemble_all_gec_only_asr0.75.pkl --is_ensemble 1 --speech 1 --model_name ensemble_all2 --special_tokens_fix 0 --threshold_constant 0.75 --spoken_gec_threshold_mode gec_only
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --output_file experiments/pr_data/confidence/Linguaskill_whisperflt/ensemble_all_gec_only_asr0.pkl --is_ensemble 1 --speech 1 --model_name ensemble_all3 --special_tokens_fix 0 --threshold_constant 0 --spoken_gec_threshold_mode gec_only
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --output_file experiments/pr_data/confidence/Linguaskill_whisperflt/ensemble_all_prod_2_1.pkl --is_ensemble 1 --speech 1 --model_name ensemble_all5 --special_tokens_fix 0 --spoken_gec_threshold_mode weighted_product --alpha 2 --beta 1
/scratches/dialfs/alta/th624/exp-th624/Calibration_Uncertainty_GEC/pr_confidence.py
/scratches/dialfs/alta/th624/exp-th624/Calibration_Uncertainty_GEC/pr_confidence.py
pr_confidence.py
pr_confidence.py
pr_confidence.py
pr_confidence.py
/scratches/dialfs/alta/th624/exp-th624/Calibration_Uncertainty_GEC/pr_confidence.py
pr_confidence.py
pr_confidence.py
pr_confidence.py
/scratches/dialfs/alta/th624/exp-th624/Calibration_Uncertainty_GEC/pr_confidence.py
pr_confidence.py
/scratches/dialfs/alta/th624/exp-th624/Calibration_Uncertainty_GEC/pr_confidence.py
pr_confidence.py
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --output_file experiments/pr_data/confidence/Linguaskill_whisperflt/ensemble_all_prod_2_1.pkl --is_ensemble 1 --speech 1 --model_name ensemble_all5 --special_tokens_fix 0 --spoken_gec_threshold_mode weighted_product --alpha 2 --beta 1
/scratches/dialfs/alta/th624/exp-th624/Calibration_Uncertainty_GEC/pr_confidence.py
pr_confidence.py
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --output_file experiments/pr_data/confidence/Linguaskill_whisperflt/ensemble_all_prod_2_1.pkl --is_ensemble 1 --speech 1 --model_name ensemble_all5 --special_tokens_fix 0 --spoken_gec_threshold_mode upper_bound
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --output_file experiments/pr_data/confidence/Linguaskill_whisperflt/ensemble_all_prod_2_1.pkl --is_ensemble 1 --speech 1 --model_name ensemble_all5 --special_tokens_fix 0 --spoken_gec_threshold_mode gec_only
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --output_file experiments/pr_data/confidence/Linguaskill_whisperflt/ensemble_all_prod_2_1.pkl --is_ensemble 1 --speech 1 --model_name ensemble_all5 --special_tokens_fix 0 --spoken_gec_threshold_mode gec_only
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --output_file experiments/pr_data/confidence/Linguaskill_whisperflt/ensemble_all_prod_2_1.pkl --is_ensemble 1 --speech 1 --model_name ensemble_all5 --special_tokens_fix 0 --spoken_gec_threshold_mode upper_bound
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --output_file experiments/pr_data/confidence/Linguaskill_whisperflt/ensemble_all_prod_2_1.pkl --is_ensemble 1 --speech 1 --model_name ensemble_all5 --special_tokens_fix 0 --spoken_gec_threshold_mode gec_only
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --output_file experiments/pr_data/confidence/Linguaskill_whisperflt/ensemble_all_prod_2_1.pkl --is_ensemble 1 --speech 1 --model_name ensemble_all5 --special_tokens_fix 0 --spoken_gec_threshold_mode asr_only
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --output_file experiments/pr_data/confidence/Linguaskill_whisperflt/ensemble_all_prod_2_1.pkl --is_ensemble 1 --speech 1 --model_name ensemble_all5 --special_tokens_fix 0 --spoken_gec_threshold_mode asr_only
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --output_file experiments/pr_data/confidence/Linguaskill_whisperflt/ensemble_all_prod_2_1.pkl --is_ensemble 1 --speech 1 --model_name ensemble_all5 --special_tokens_fix 0 --spoken_gec_threshold_mode upper_bound_stc
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --output_file experiments/pr_data/confidence/Linguaskill_whisperflt/ensemble_all_prod_2_1.pkl --is_ensemble 1 --speech 1 --model_name ensemble_all5 --special_tokens_fix 0 --spoken_gec_threshold_mode upper_bound_stc
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --output_file experiments/pr_data/confidence/Linguaskill_whisperflt/ensemble_all_prod_2_1.pkl --is_ensemble 1 --speech 1 --model_name ensemble_all5 --special_tokens_fix 0 --spoken_gec_threshold_mode upper_bound_stc
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --output_file experiments/pr_data/confidence/Linguaskill_whisperflt/ensemble_all_prod_2_1.pkl --is_ensemble 1 --speech 1 --model_name ensemble_all5 --special_tokens_fix 0 --spoken_gec_threshold_mode upper_bound_stc
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --output_file experiments/pr_data/confidence/Linguaskill_whisperflt/ensemble_all_prod_2_1.pkl --is_ensemble 1 --speech 1 --model_name ensemble_all5 --special_tokens_fix 0 --spoken_gec_threshold_mode upper_bound
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --output_file experiments/pr_data/confidence/Linguaskill_whisperflt/ensemble_all_prod_2_1.pkl --is_ensemble 1 --speech 1 --model_name ensemble_all5 --special_tokens_fix 0 --spoken_gec_threshold_mode upper_bound
/scratches/dialfs/alta/th624/exp-th624/Calibration_Uncertainty_GEC/pr_confidence.py
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --output_file experiments/pr_data/confidence/Linguaskill_whisperflt/ensemble_all_prod_2_1.pkl --is_ensemble 1 --speech 1 --model_name ensemble_all5 --special_tokens_fix 0 --spoken_gec_threshold_mode upper_bound
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --output_file experiments/pr_data/confidence/Linguaskill_whisperflt/ensemble_all_asr_only_gec0_mod.pkl --is_ensemble 1 --speech 1 --model_name ensemble_all1 --special_tokens_fix 0 --spoken_gec_threshold_mode asr_only --errant_mod 1
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --output_file experiments/pr_data/confidence/Linguaskill_whisperflt/ensemble_all_gec_only_asr0.75_mod.pkl --is_ensemble 1 --speech 1 --model_name ensemble_all2 --special_tokens_fix 0 --threshold_constant 0.75 --spoken_gec_threshold_mode gec_only --errant_mod 1
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --output_file experiments/pr_data/confidence/Linguaskill_whisperflt/ensemble_all_gec_only_asr0_mod.pkl --is_ensemble 1 --speech 1 --model_name ensemble_all3 --special_tokens_fix 0 --threshold_constant 0 --spoken_gec_threshold_mode gec_only --errant_mod 1
/scratches/dialfs/alta/th624/exp-th624/Calibration_Uncertainty_GEC/pr_confidence.py
/scratches/dialfs/alta/th624/exp-th624/Calibration_Uncertainty_GEC/pr_confidence.py
/scratches/dialfs/alta/th624/exp-th624/Calibration_Uncertainty_GEC/pr_confidence.py
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --output_file experiments/pr_data/confidence/Linguaskill_whisperflt/ensemble_all_asr_only_gec0_mod.pkl --is_ensemble 1 --speech 1 --model_name ensemble_all1 --special_tokens_fix 0 --spoken_gec_threshold_mode asr_only --errant_mod 1
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --output_file experiments/pr_data/confidence/Linguaskill_whisperflt/ensemble_all_gec_only_asr0.75_mod.pkl --is_ensemble 1 --speech 1 --model_name ensemble_all2 --special_tokens_fix 0 --threshold_constant 0.75 --spoken_gec_threshold_mode gec_only --errant_mod 1
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --output_file experiments/pr_data/confidence/Linguaskill_whisperflt/ensemble_all_gec_only_asr0_mod.pkl --is_ensemble 1 --speech 1 --model_name ensemble_all3 --special_tokens_fix 0 --threshold_constant 0 --spoken_gec_threshold_mode gec_only --errant_mod 1
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --output_file experiments/pr_data/confidence/Linguaskill_whisperflt/ensemble_all_asr_only_gec0_mod.pkl --is_ensemble 1 --speech 1 --model_name ensemble_all1 --special_tokens_fix 0 --spoken_gec_threshold_mode asr_only --errant_mod 1 --input_file ../data/Linguaskill/preprocessed_whisperflt/ls_toy.inc --target_file ../data/Linguaskill/preprocessed_whisperflt/ls_toy.corr
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --output_file experiments/pr_data/confidence/Linguaskill_whisperflt/ensemble_all_asr_only_gec0_mod.pkl --is_ensemble 1 --speech 1 --model_name ensemble_all1 --special_tokens_fix 0 --spoken_gec_threshold_mode asr_only --errant_mod 1 --input_file ../data/Linguaskill/preprocessed_whisperflt/ls_toy.inc --target_file ../data/Linguaskill/preprocessed_whisperflt/ls_toy.corr
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --output_file experiments/pr_data/confidence/Linguaskill_whisperflt/ensemble_all_asr_only_gec0_mod.pkl --is_ensemble 1 --speech 1 --model_name ensemble_all1 --special_tokens_fix 0 --spoken_gec_threshold_mode asr_only --errant_mod 1 --input_file ../data/Linguaskill/preprocessed_whisperflt/ls_toy.inc --target_file ../data/Linguaskill/preprocessed_whisperflt/ls_toy.corr
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --output_file experiments/pr_data/confidence/Linguaskill_whisperflt/ensemble_all_asr_only_gec0_mod.pkl --is_ensemble 1 --speech 1 --model_name ensemble_all1 --special_tokens_fix 0 --spoken_gec_threshold_mode asr_only --errant_mod 1 --input_file ../data/Linguaskill/preprocessed_whisperflt/ls_toy.inc --target_file ../data/Linguaskill/preprocessed_whisperflt/ls_toy.corr --n_steps 10
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --output_file experiments/pr_data/confidence/Linguaskill_whisperflt/ensemble_all_asr_only_gec0_mod.pkl --is_ensemble 1 --speech 1 --model_name ensemble_all1 --special_tokens_fix 0 --spoken_gec_threshold_mode asr_only --errant_mod 1
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --output_file experiments/pr_data/confidence/Linguaskill_whisperflt/ensemble_all_asr_only_gec0_mod.pkl --is_ensemble 1 --speech 1 --model_name ensemble_all1 --special_tokens_fix 0 --spoken_gec_threshold_mode asr_only --errant_mod 1
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --output_file experiments/pr_data/confidence/Linguaskill_whisperflt/ensemble_all_prod_1_1_mod.pkl --is_ensemble 1 --speech 1 --model_name ensemble_all5 --special_tokens_fix 0 --spoken_gec_threshold_mode weighted_product --alpha 1 --beta 1 --errant_mod 1
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --output_file experiments/pr_data/confidence/Linguaskill_whisperflt/ensemble_all_asr_only_gec0_mod.pkl --is_ensemble 1 --speech 1 --model_name ensemble_all1 --special_tokens_fix 0 --spoken_gec_threshold_mode asr_only --errant_mod 1
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --output_file experiments/pr_data/confidence/Linguaskill_whisperflt/ensemble_all_asr_only_gec0_mod.pkl --is_ensemble 1 --speech 1 --model_name ensemble_all1 --special_tokens_fix 0 --spoken_gec_threshold_mode upper_bound --errant_mod 1
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --output_file experiments/pr_data/confidence/Linguaskill_whisperflt/ensemble_all_prod_2_1_mod.pkl --is_ensemble 1 --speech 1 --model_name ensemble_all6 --special_tokens_fix 0 --spoken_gec_threshold_mode weighted_product --alpha 2 --beta 1 --errant_mod 1
pr_confidence.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --output_file experiments/pr_data/confidence/Linguaskill_whisperflt/ensemble_all_asr_only_gec0.5_mod.pkl --is_ensemble 1 --speech 1 --model_name ensemble_all1 --special_tokens_fix 0 --spoken_gec_threshold_mode asr_only --threshold_constant 0.5 --errant_mod 1
/scratches/dialfs/alta/th624/exp-th624/Calibration_Uncertainty_GEC/pr_confidence.py
/scratches/dialfs/alta/th624/exp-th624/Calibration_Uncertainty_GEC/pr_confidence.py
/scratches/dialfs/alta/th624/exp-th624/Calibration_Uncertainty_GEC/pr_confidence.py
