max_vote.py --source_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --target_files experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred --output_file experiments/prediction_files/conll/max_vote.txt --min_count 2
max_vote.py --source_file /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --target_files experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred --output_file experiments/prediction_files/fce/max_vote.pred --min_count 2
max_vote.py --source_file ../data/BEA2019/bea2019test.txt --target_files experiments/prediction_files/bea/bert.pred experiments/prediction_files/bea/roberta.pred experiments/prediction_files/bea/xlnet.pred --output_file experiments/prediction_files/bea/max_vote.pred --min_count 2
max_vote.py --source_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --target_files experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred --output_file experiments/prediction_files/conll/max_vote1.txt --min_count 1
max_vote.py --source_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --target_files experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred --output_file experiments/prediction_files/conll/max_vote1.pred --min_count 1
max_vote.py --source_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --target_files experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred --output_file experiments/prediction_files/conll/max_vote2.pred --min_count 2
max_vote.py --source_file /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --target_files experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred --output_file experiments/prediction_files/fce/max_vote1.pred --min_count 1
max_vote.py --source_file /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --target_files experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred --output_file experiments/prediction_files/fce/max_vote3.pred --min_count 3
max_vote.py --source_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --target_files experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred --output_file experiments/prediction_files/conll/max_vote3.pred --min_count 3
max_vote.py --source_file /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --target_files experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred --output_file experiments/prediction_files/fce/max_vote3.pred --min_count 3
max_vote.py --source_file ../data/BEA2019/bea2019test.txt --target_files experiments/prediction_files/bea/bert.pred experiments/prediction_files/bea/roberta.pred experiments/prediction_files/bea/xlnet.pred --output_file experiments/prediction_files/bea/max_vote1.pred --min_count 1
max_vote.py --source_file ../data/BEA2019/bea2019test.txt --target_files experiments/prediction_files/bea/bert.pred experiments/prediction_files/bea/roberta.pred experiments/prediction_files/bea/xlnet.pred --output_file experiments/prediction_files/bea/max_vote3.pred --min_count 3
max_vote.py --source_file ../data/ELIT/input.txt --target_files experiments/prediction_files/elit/bert.pred experiments/prediction_files/elit/roberta.pred experiments/prediction_files/elit/xlnet.pred --output_file experiments/prediction_files/elit/max_vote2.pred --min_count 2
max_vote.py --source_file ../data/ELIT/input.txt --target_files experiments/prediction_files/elit/bert.pred experiments/prediction_files/elit/roberta.pred experiments/prediction_files/elit/xlnet.pred --output_file experiments/prediction_files/elit/max_vote3.pred --min_count 3
max_vote.py --source_file ../data/Linguaskill/preprocessed/ls_test.inc --target_files experiments/prediction_files/Linguaskill_test/bert.pred experiments/prediction_files/Linguaskill_test/roberta.pred experiments/prediction_files/Linguaskill_test/xlnet.pred experiments/prediction_files/Linguaskill_test_FineTuned/bert.pred experiments/prediction_files/Linguaskill_test_FineTuned/roberta.pred experiments/prediction_files/Linguaskill_test_FineTuned/xlnet.pred --output_file experiments/prediction_files/Linguaskill_test_comb/max_vote_6.pred --min_count 6
max_vote.py --source_file ../data/Linguaskill/preprocessed/ls_test.inc --target_files experiments/prediction_files/Linguaskill_test/bert.pred experiments/prediction_files/Linguaskill_test/roberta.pred experiments/prediction_files/Linguaskill_test/xlnet.pred experiments/prediction_files/Linguaskill_test_FineTuned/bert.pred experiments/prediction_files/Linguaskill_test_FineTuned/roberta.pred experiments/prediction_files/Linguaskill_test_FineTuned/xlnet.pred --output_file experiments/prediction_files/Linguaskill_test_comb/max_vote_6.pred --min_count 6
max_vote.py --source_file ../data/Linguaskill/preprocessed/ls_test.inc --target_files experiments/prediction_files/Linguaskill_test/bert.pred experiments/prediction_files/Linguaskill_test/roberta.pred experiments/prediction_files/Linguaskill_test/xlnet.pred experiments/prediction_files/Linguaskill_test_FineTuned/bert.pred experiments/prediction_files/Linguaskill_test_FineTuned/roberta.pred experiments/prediction_files/Linguaskill_test_FineTuned/xlnet.pred --output_file experiments/prediction_files/Linguaskill_test_comb/max_vote_5.pred --min_count 5
max_vote.py --source_file ../data/Linguaskill/preprocessed/ls_test.inc --target_files experiments/prediction_files/Linguaskill_test/bert.pred experiments/prediction_files/Linguaskill_test/roberta.pred experiments/prediction_files/Linguaskill_test/xlnet.pred experiments/prediction_files/Linguaskill_test_FineTuned/bert.pred experiments/prediction_files/Linguaskill_test_FineTuned/roberta.pred experiments/prediction_files/Linguaskill_test_FineTuned/xlnet.pred --output_file experiments/prediction_files/Linguaskill_test_comb/max_vote_4.pred --min_count 4
max_vote.py --source_file ../data/Linguaskill/preprocessed/ls_test.inc --target_files experiments/prediction_files/Linguaskill_test/bert.pred experiments/prediction_files/Linguaskill_test/roberta.pred experiments/prediction_files/Linguaskill_test/xlnet.pred experiments/prediction_files/Linguaskill_test_FineTuned/bert.pred experiments/prediction_files/Linguaskill_test_FineTuned/roberta.pred experiments/prediction_files/Linguaskill_test_FineTuned/xlnet.pred --output_file experiments/prediction_files/Linguaskill_test_comb/max_vote_3.pred --min_count 3
max_vote.py --source_file ../data/Linguaskill/preprocessed/ls_test.inc --target_files experiments/prediction_files/Linguaskill_test/bert.pred experiments/prediction_files/Linguaskill_test/roberta.pred experiments/prediction_files/Linguaskill_test/xlnet.pred experiments/prediction_files/Linguaskill_test_FineTuned/bert.pred experiments/prediction_files/Linguaskill_test_FineTuned/roberta.pred experiments/prediction_files/Linguaskill_test_FineTuned/xlnet.pred --output_file experiments/prediction_files/Linguaskill_test_comb/max_vote_2.pred --min_count 2
