mbr.py --pred_files experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/conll/mbr.pred
mbr.py --pred_files experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/conll/mbr.pred
mbr.py --pred_files experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/conll/mbr.pred
mbr.py --pred_files experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/conll/mbr.pred
mbr.py --pred_files experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/conll/mbr.pred
mbr.py --pred_files experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/conll/mbr.pred
mbr.py --pred_files experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/conll/mbr.pred
mbr.py --pred_files experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred --input ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --outfile experiments/prediction_files/conll/mbr.pred
mbr.py --pred_files experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/fce/mbr.pred
mbr.py --pred_files experiments/prediction_files/bea/bert.pred experiments/prediction_files/bea/roberta.pred experiments/prediction_files/bea/xlnet.pred --input ../data/BEA2019/bea2019test.txt --outfile experiments/prediction_files/bea/mbr.pred
mbr.py --pred_files experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred --input ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --outfile experiments/prediction_files/conll/mbr_jaccard.pred --reward jaccard
mbr.py --pred_files experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred --input ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --outfile experiments/prediction_files/conll/mbr_jaccard.pred --reward jaccard
mbr.py --pred_files experiments/prediction_files/bea/bert.pred experiments/prediction_files/bea/roberta.pred experiments/prediction_files/bea/xlnet.pred --input ../data/BEA2019/bea2019test.txt --outfile experiments/prediction_files/bea/mbr_jaccard.pred --reward jaccard
mbr.py --pred_files experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/fce/mbr_jaccard.pred --reward jaccard
mbr.py --pred_files experiments/prediction_files/conll/max_vote1.pred experiments/prediction_files/conll/max_vote2.pred experiments/prediction_files/conll/max_vote3.pred --input ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --outfile experiments/prediction_files/conll/mbr_m1-3.pred --reward jaccard
mbr.py --pred_files experiments/prediction_files/fce/max_vote1.pred experiments/prediction_files/fce/max_vote2.pred experiments/prediction_files/fce/max_vote3.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/fce/mbr_m1-3.pred --reward jaccard
mbr.py --pred_files experiments/prediction_files/fce/max_vote1.pred experiments/prediction_files/fce/max_vote2.pred experiments/prediction_files/fce/max_vote3.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/fce/mbr_m1-3.pred --reward jaccard
mbr.py --pred_files experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred experiments/prediction_files/fce/max_vote2.pred experiments/prediction_files/fce/max_vote3.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/fce/mbr_m2-3_brx.pred --reward jaccard
mbr.py --pred_files experiments/prediction_files/bea/max_vote1.pred experiments/prediction_files/bea/max_vote2.pred experiments/prediction_files/bea/max_vote3.pred --input ../data/BEA2019/bea2019test.txt --outfile experiments/prediction_files/bea/mbr_m1-3.pred --reward jaccard
mbr.py --pred_files experiments/prediction_files/bea/bert.pred experiments/prediction_files/bea/roberta.pred experiments/prediction_files/bea/xlnet.pred experiments/prediction_files/bea/max_vote2.pred experiments/prediction_files/bea/max_vote3.pred --input ../data/BEA2019/bea2019test.txt --outfile experiments/prediction_files/bea/mbr_m2-3_brx.pred --reward jaccard
mbr.py --pred_files experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/fce/mbr_upper.pred --reward jaccard --upperbound --ref /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.corr
mbr.py --pred_files experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/fce/mbr_upper.pred --reward jaccard --upperbound --ref /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.corr
mbr.py --pred_files experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/fce/mbr_upper.pred --reward jaccard --upperbound --ref /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.corr
mbr.py --pred_files experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/fce/mbr_prec.pred --reward prec
mbr.py --pred_files experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/fce/mbr_prec.pred --reward prec
mbr.py --pred_files experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/fce/mbr_prec.pred --reward prec
mbr.py --pred_files experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/fce/mbr_rec.pred --reward rec
mbr.py --pred_files experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/fce/mbr_prec.pred --reward prec
mbr.py --pred_files experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/fce/mbr_rec.pred --reward rec
mbr.py --pred_files experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/fce/mbr_rec_upper.pred --reward rec --upperbound --ref /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.corr
mbr.py --pred_files experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/fce/mbr_prec_upper.pred --reward prec --upperbound --ref /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.corr
mbr.py --pred_files experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/fce/mbr_agree_upper.pred --reward agreement --upperbound --ref /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.corr
mbr.py --pred_files experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/fce/mbr_f05.pred --reward f05
mbr.py --pred_files experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/fce/mbr_f05_upper.pred --reward f05 --upperbound --ref /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.corr
mbr.py --pred_files experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred --input ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --outfile experiments/prediction_files/conll/mbr_rec.pred --reward rec
mbr.py --pred_files experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred --input ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --outfile experiments/prediction_files/conll/mbr_prec.pred --reward prec
mbr.py --pred_files experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred --input ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --outfile experiments/prediction_files/conll/mbr_f05.pred --reward f05
mbr.py --pred_files experiments/prediction_files/bea/bert.pred experiments/prediction_files/bea/roberta.pred experiments/prediction_files/bea/xlnet.pred --input ../data/BEA2019/bea2019test.txt --outfile experiments/prediction_files/bea/mbr_rec.pred --reward rec
mbr.py --pred_files experiments/prediction_files/bea/bert.pred experiments/prediction_files/bea/roberta.pred experiments/prediction_files/bea/xlnet.pred --input ../data/BEA2019/bea2019test.txt --outfile experiments/prediction_files/bea/mbr_prec.pred --reward prec
mbr.py --pred_files experiments/prediction_files/bea/bert.pred experiments/prediction_files/bea/roberta.pred experiments/prediction_files/bea/xlnet.pred --input ../data/BEA2019/bea2019test.txt --outfile experiments/prediction_files/bea/mbr_f05.pred --reward f05
mbr.py --pred_files experiments/prediction_files/conll/max_vote1.pred experiments/prediction_files/conll/max_vote2.pred experiments/prediction_files/conll/max_vote3.pred --input ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --outfile experiments/prediction_files/conll/mbr_m1-3.pred --reward jaccard
mbr.py --pred_files experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred experiments/prediction_files/conll/max_vote2.pred experiments/prediction_files/conll/max_vote3.pred --input ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --outfile experiments/prediction_files/conll/mbr_m2-3_brx.pred --reward jaccard
mbr.py --pred_files experiments/prediction_files/elit/bert.pred experiments/prediction_files/elit/roberta.pred experiments/prediction_files/elit/xlnet.pred --input ../data/ELIT/input.txt --outfile experiments/prediction_files/elit/mbr_prec_brx.pred --reward prec
mbr.py --pred_files experiments/prediction_files/elit/bert.pred experiments/prediction_files/elit/roberta.pred experiments/prediction_files/elit/xlnet.pred --input ../data/ELIT/input.txt --outfile experiments/prediction_files/elit/mbr_jac_brx.pred --reward jaccard
mbr.py --pred_files experiments/prediction_files/elit/bert.pred experiments/prediction_files/elit/roberta.pred experiments/prediction_files/elit/xlnet.pred --input ../data/ELIT/input.txt --outfile experiments/prediction_files/elit/mbr_jac_brx.pred --reward f05
mbr.py --pred_files experiments/prediction_files/elit/bert.pred experiments/prediction_files/elit/roberta.pred experiments/prediction_files/elit/xlnet.pred --input ../data/ELIT/input.txt --outfile experiments/prediction_files/elit/mbr_f05_brx.pred --reward f05
mbr.py --pred_files experiments/prediction_files/elit/bert.pred experiments/prediction_files/elit/roberta.pred experiments/prediction_files/elit/xlnet.pred experiments/prediction_files/elit/max_vote2.pred --input ../data/ELIT/input.txt --outfile experiments/prediction_files/elit/mbr_jac_m2_brx.pred --reward jaccard
mbr.py --pred_files experiments/prediction_files/elit/bert.pred experiments/prediction_files/elit/roberta.pred experiments/prediction_files/elit/xlnet.pred experiments/prediction_files/elit/max_vote2.pred --input ../data/ELIT/input.txt --outfile experiments/prediction_files/elit/mbr_prec_m2_brx.pred --reward prec
mbr.py --pred_files experiments/prediction_files/elit/bert.pred experiments/prediction_files/elit/roberta.pred experiments/prediction_files/elit/xlnet.pred experiments/prediction_files/elit/max_vote2.pred --input ../data/ELIT/input.txt --outfile experiments/prediction_files/elit/mbr_f05_m2_brx.pred --reward f05
mbr.py --pred_files experiments/prediction_files/elit/bert.pred experiments/prediction_files/elit/roberta.pred experiments/prediction_files/elit/xlnet.pred experiments/prediction_files/elit/max_vote2.pred experiments/prediction_files/elit/max_vote3.pred --input ../data/ELIT/input.txt --outfile experiments/prediction_files/elit/mbr_prec_m23_brx.pred --reward prec
mbr.py --pred_files experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred experiments/prediction_files/conll/max_vote2.pred experiments/prediction_files/conll/max_vote3.pred --input ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --outfile experiments/prediction_files/conll/mbr_prec_m23_brx.pred --reward prec
mbr.py --pred_files experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred experiments/prediction_files/conll/max_vote2.pred experiments/prediction_files/conll/max_vote3.pred --input ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --outfile experiments/prediction_files/conll/mbr_f05_m23_brx.pred --reward f05
mbr.py --pred_files experiments/prediction_files/bea/bert.pred experiments/prediction_files/bea/roberta.pred experiments/prediction_files/bea/xlnet.pred experiments/prediction_files/bea/max_vote2.pred experiments/prediction_files/bea/max_vote3.pred --input ../data/BEA2019/bea2019test.txt --outfile experiments/prediction_files/bea/mbr_f05_m23_brx.pred --reward f05
mbr.py --pred_files experiments/prediction_files/bea/bert.pred experiments/prediction_files/bea/roberta.pred experiments/prediction_files/bea/xlnet.pred experiments/prediction_files/bea/max_vote2.pred experiments/prediction_files/bea/max_vote3.pred --input ../data/BEA2019/bea2019test.txt --outfile experiments/prediction_files/bea/mbr_prec_m23_brx.pred --reward prec
mbr.py --pred_files experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred experiments/prediction_files/fce/max_vote2.pred experiments/prediction_files/fce/max_vote3.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/fce/mbr_prec_m23_brx.pred --reward prec
mbr.py --pred_files experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred experiments/prediction_files/fce/max_vote2.pred experiments/prediction_files/fce/max_vote3.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/fce/mbr_f05_m23_brx.pred --reward f05
mbr.py --pred_files experiments/prediction_files/Linguaskill_test/bert.pred experiments/prediction_files/Linguaskill_test/roberta.pred experiments/prediction_files/Linguaskill_test/xlnet.pred --input ../data/Linguaskill/preprocessed/ls_test.inc --reward_f05 --outfile experiments/prediction_files/Linguaskill_test/mbr_f05_NoVote.pred
mbr.py --pred_files experiments/prediction_files/Linguaskill_test/bert.pred experiments/prediction_files/Linguaskill_test/roberta.pred experiments/prediction_files/Linguaskill_test/xlnet.pred --input ../data/Linguaskill/preprocessed/ls_test.inc --reward f05 --outfile experiments/prediction_files/Linguaskill_test/mbr_f05_NoVote.pred
mbr.py --pred_files experiments/prediction_files/Linguaskill_test/bert.pred experiments/prediction_files/Linguaskill_test/roberta.pred experiments/prediction_files/Linguaskill_test/xlnet.pred --input ../data/Linguaskill/preprocessed/ls_test.inc --reward prec --outfile experiments/prediction_files/Linguaskill_test/mbr_p_NoVote.pred
mbr.py --pred_files experiments/prediction_files/Linguaskill_test_FineTuned/bert.pred experiments/prediction_files/Linguaskill_test_FineTuned/roberta.pred experiments/prediction_files/Linguaskill_test_FineTuned/xlnet.pred --input ../data/Linguaskill/preprocessed/ls_test.inc --reward f05 --outfile experiments/prediction_files/Linguaskill_test_FineTuned/mbr_f05_NoVote.pred
mbr.py --pred_files experiments/prediction_files/Linguaskill_test_FineTuned/bert.pred experiments/prediction_files/Linguaskill_test_FineTuned/roberta.pred experiments/prediction_files/Linguaskill_test_FineTuned/xlnet.pred --input ../data/Linguaskill/preprocessed/ls_test.inc --reward f05 --outfile experiments/prediction_files/Linguaskill_test_FineTuned/mbr_f05_NoVote.pred
mbr.py --pred_files experiments/prediction_files/Linguaskill_test_FineTuned/bert.pred experiments/prediction_files/Linguaskill_test_FineTuned/roberta.pred experiments/prediction_files/Linguaskill_test_FineTuned/xlnet.pred --input ../data/Linguaskill/preprocessed/ls_test.inc --reward prec --outfile experiments/prediction_files/Linguaskill_test_FineTuned/mbr_p_NoVote.pred
mbr.py --pred_files experiments/prediction_files/Linguaskill_test_FineTuned/bert.pred experiments/prediction_files/Linguaskill_test_FineTuned/roberta.pred experiments/prediction_files/Linguaskill_test_FineTuned/xlnet.pred --input ../data/Linguaskill/preprocessed/ls_test.inc --reward prec --outfile experiments/prediction_files/Linguaskill_test_FineTuned/mbr_p_NoVote.pred
mbr.py --pred_files experiments/prediction_files/Linguaskill_test/bert.pred experiments/prediction_files/Linguaskill_test/roberta.pred experiments/prediction_files/Linguaskill_test/xlnet.pred experiments/prediction_files/Linguaskill_test_FineTuned/bert.pred experiments/prediction_files/Linguaskill_test_FineTuned/roberta.pred experiments/prediction_files/Linguaskill_test_FineTuned/xlnet.pred --input ../data/Linguaskill/preprocessed/ls_test.inc --reward prec --outfile experiments/prediction_files/Linguaskill_test_comb/mbr_p_NoVote.predmbr.py --pred_files experiments/prediction_files/Linguaskill_test/bert.pred experiments/prediction_files/Linguaskill_test/roberta.pred experiments/prediction_files/Linguaskill_test/xlnet.pred experiments/prediction_files/Linguaskill_test_FineTuned/bert.pred experiments/prediction_files/Linguaskill_test_FineTuned/roberta.pred experiments/prediction_files/Linguaskill_test_FineTuned/xlnet.pred --input ../data/Linguaskill/preprocessed/ls_test.inc --reward rec --outfile experiments/prediction_files/Linguaskill_test_comb/mbr_r_NoVote.pred
mbr.py --pred_files experiments/prediction_files/Linguaskill_test_comb/max_vote_2.pred experiments/prediction_files/Linguaskill_test_comb/max_vote_3.pred experiments/prediction_files/Linguaskill_test_comb/max_vote_4.pred experiments/prediction_files/Linguaskill_test_comb/max_vote_5.pred experiments/prediction_files/Linguaskill_test_comb/max_vote_6.pred experiments/prediction_files/Linguaskill_test/bert.pred experiments/prediction_files/Linguaskill_test/roberta.pred experiments/prediction_files/Linguaskill_test/xlnet.pred experiments/prediction_files/Linguaskill_test_FineTuned/bert.pred experiments/prediction_files/Linguaskill_test_FineTuned/roberta.pred experiments/prediction_files/Linguaskill_test_FineTuned/xlnet.pred --input ../data/Linguaskill/preprocessed/ls_test.inc --reward prec --outfile experiments/prediction_files/Linguaskill_test_comb/mbr_p_NoVote.predmbr.py --pred_files experiments/prediction_files/Linguaskill_test/bert.pred experiments/prediction_files/Linguaskill_test/roberta.pred experiments/prediction_files/Linguaskill_test/xlnet.pred experiments/prediction_files/Linguaskill_test_FineTuned/bert.pred experiments/prediction_files/Linguaskill_test_FineTuned/roberta.pred experiments/prediction_files/Linguaskill_test_FineTuned/xlnet.pred --input ../data/Linguaskill/preprocessed/ls_test.inc --reward f05 --outfile experiments/prediction_files/Linguaskill_test_comb/mbr_f05_vote23456.pred
mbr.py --pred_files experiments/prediction_files/Linguaskill_test_comb/max_vote_4.pred experiments/prediction_files/Linguaskill_test_comb/max_vote_5.pred experiments/prediction_files/Linguaskill_test_comb/max_vote_6.pred experiments/prediction_files/Linguaskill_test/bert.pred experiments/prediction_files/Linguaskill_test/roberta.pred experiments/prediction_files/Linguaskill_test/xlnet.pred experiments/prediction_files/Linguaskill_test_FineTuned/bert.pred experiments/prediction_files/Linguaskill_test_FineTuned/roberta.pred experiments/prediction_files/Linguaskill_test_FineTuned/xlnet.pred --input ../data/Linguaskill/preprocessed/ls_test.inc --reward prec --outfile experiments/prediction_files/Linguaskill_test_comb/mbr_p_NoVote.predmbr.py --pred_files experiments/prediction_files/Linguaskill_test/bert.pred experiments/prediction_files/Linguaskill_test/roberta.pred experiments/prediction_files/Linguaskill_test/xlnet.pred experiments/prediction_files/Linguaskill_test_FineTuned/bert.pred experiments/prediction_files/Linguaskill_test_FineTuned/roberta.pred experiments/prediction_files/Linguaskill_test_FineTuned/xlnet.pred --input ../data/Linguaskill/preprocessed/ls_test.inc --reward f05 --outfile experiments/prediction_files/Linguaskill_test_comb/mbr_f05_vote456.predmbr.py --pred_files experiments/prediction_files/Linguaskill_test_comb/max_vote_4.pred experiments/prediction_files/Linguaskill_test_comb/max_vote_5.pred experiments/prediction_files/Linguaskill_test_comb/max_vote_6.pred experiments/prediction_files/Linguaskill_test/bert.pred experiments/prediction_files/Linguaskill_test/roberta.pred experiments/prediction_files/Linguaskill_test/xlnet.pred experiments/prediction_files/Linguaskill_test_FineTuned/bert.pred experiments/prediction_files/Linguaskill_test_FineTuned/roberta.pred experiments/prediction_files/Linguaskill_test_FineTuned/xlnet.pred --input ../data/Linguaskill/preprocessed/ls_test.inc --reward prec --outfile experiments/prediction_files/Linguaskill_test_comb/mbr_p_NoVote.predmbr.py --pred_files experiments/prediction_files/Linguaskill_test/bert.pred experiments/prediction_files/Linguaskill_test/roberta.pred experiments/prediction_files/Linguaskill_test/xlnet.pred experiments/prediction_files/Linguaskill_test_FineTuned/bert.pred experiments/prediction_files/Linguaskill_test_FineTuned/roberta.pred experiments/prediction_files/Linguaskill_test_FineTuned/xlnet.pred --input ../data/Linguaskill/preprocessed/ls_test.inc --reward f05 --outfile experiments/prediction_files/Linguaskill_test_comb/mbr_f05_vote456.pred
