mbr_lim.py --universe experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred --lims experiments/prediction_files/conll/max_vote2.pred experiments/prediction_files/conll/max_vote3.pred --input ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --outfile experiments/prediction_files/conll/lim_prec_m23.pred --reward prec
mbr_lim.py --universe experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred --lims experiments/prediction_files/conll/max_vote2.pred experiments/prediction_files/conll/max_vote3.pred --input ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --outfile experiments/prediction_files/conll/lim_prec_m23.pred --reward prec
mbr_lim.py --universe experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred --lims experiments/prediction_files/conll/max_vote2.pred experiments/prediction_files/conll/max_vote3.pred --input ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --outfile experiments/prediction_files/conll/lim_prec_m23.pred --reward prec
mbr_lim.py --universe experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred --lims experiments/prediction_files/conll/max_vote2.pred experiments/prediction_files/conll/max_vote3.pred --input ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --outfile experiments/prediction_files/conll/lim_prec_m23.pred --reward prec
mbr_lim.py --universe experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred --lims experiments/prediction_files/conll/max_vote1.pred experiments/prediction_files/conll/max_vote3.pred --input ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --outfile experiments/prediction_files/conll/lim_prec_m13.pred --reward prec
mbr_lim.py --universe experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred --lims experiments/prediction_files/conll/max_vote1.pred experiments/prediction_files/conll/max_vote3.pred --input ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --outfile experiments/prediction_files/conll/lim_rec_m13.pred --reward rec
mbr_lim.py --universe experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred --lims experiments/prediction_files/conll/max_vote1.pred experiments/prediction_files/conll/max_vote3.pred --input ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --outfile experiments/prediction_files/conll/lim_f05_m13.pred --reward f05
mbr_lim.py --universe experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred --lims experiments/prediction_files/conll/max_vote1.pred experiments/prediction_files/conll/max_vote3.pred --input ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --outfile experiments/prediction_files/conll/lim_jac_m13.pred --reward jaccard
mbr_lim.py --universe experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred --lims experiments/prediction_files/conll/max_vote2.pred experiments/prediction_files/conll/max_vote3.pred --input ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --outfile experiments/prediction_files/conll/lim_rec_m23.pred --reward rec
mbr_lim.py --universe experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred --lims experiments/prediction_files/conll/max_vote2.pred experiments/prediction_files/conll/max_vote3.pred --input ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --outfile experiments/prediction_files/conll/lim_f05_m23.pred --reward f05
mbr_lim.py --universe experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred --lims experiments/prediction_files/conll/max_vote2.pred experiments/prediction_files/conll/max_vote3.pred --input ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --outfile experiments/prediction_files/conll/lim_jac_m23.pred --reward jaccard
mbr_lim.py --universe experiments/prediction_files/bea/bert.pred experiments/prediction_files/bea/roberta.pred experiments/prediction_files/bea/xlnet.pred --lims experiments/prediction_files/bea/max_vote1.pred experiments/prediction_files/bea/max_vote3.pred --input ../data/BEA2019/bea2019test.txt --outfile experiments/prediction_files/bea/mbr_lim_rec_m13.pred --reward rec
mbr_lim.py --universe experiments/prediction_files/bea/bert.pred experiments/prediction_files/bea/roberta.pred experiments/prediction_files/bea/xlnet.pred --lims experiments/prediction_files/bea/max_vote2.pred experiments/prediction_files/bea/max_vote3.pred --input ../data/BEA2019/bea2019test.txt --outfile experiments/prediction_files/bea/mbr_lim_rec_m23.pred --reward rec
mbr_lim.py --universe experiments/prediction_files/bea/bert.pred experiments/prediction_files/bea/roberta.pred experiments/prediction_files/bea/xlnet.pred --lims experiments/prediction_files/bea/max_vote1.pred experiments/prediction_files/bea/max_vote3.pred --input ../data/BEA2019/bea2019test.txt --outfile experiments/prediction_files/bea/mbr_lim_prec_m13.pred --reward prec
mbr_lim.py --universe experiments/prediction_files/bea/bert.pred experiments/prediction_files/bea/roberta.pred experiments/prediction_files/bea/xlnet.pred --lims experiments/prediction_files/bea/max_vote2.pred experiments/prediction_files/bea/max_vote3.pred --input ../data/BEA2019/bea2019test.txt --outfile experiments/prediction_files/bea/mbr_lim_prec_m23.pred --reward prec
mbr_lim.py --universe experiments/prediction_files/bea/bert.pred experiments/prediction_files/bea/roberta.pred experiments/prediction_files/bea/xlnet.pred --lims experiments/prediction_files/bea/max_vote1.pred experiments/prediction_files/bea/max_vote3.pred --input ../data/BEA2019/bea2019test.txt --outfile experiments/prediction_files/bea/mbr_lim_f05_m13.pred --reward f05
mbr_lim.py --universe experiments/prediction_files/bea/bert.pred experiments/prediction_files/bea/roberta.pred experiments/prediction_files/bea/xlnet.pred --lims experiments/prediction_files/bea/max_vote2.pred experiments/prediction_files/bea/max_vote3.pred --input ../data/BEA2019/bea2019test.txt --outfile experiments/prediction_files/bea/mbr_lim_f05_m23.pred --reward f05
mbr_lim.py --universe experiments/prediction_files/bea/bert.pred experiments/prediction_files/bea/roberta.pred experiments/prediction_files/bea/xlnet.pred --lims experiments/prediction_files/bea/max_vote1.pred experiments/prediction_files/bea/max_vote3.pred --input ../data/BEA2019/bea2019test.txt --outfile experiments/prediction_files/bea/mbr_lim_jac_m13.pred --reward jaccard
mbr_lim.py --universe experiments/prediction_files/bea/bert.pred experiments/prediction_files/bea/roberta.pred experiments/prediction_files/bea/xlnet.pred --lims experiments/prediction_files/bea/max_vote2.pred experiments/prediction_files/bea/max_vote3.pred --input ../data/BEA2019/bea2019test.txt --outfile experiments/prediction_files/bea/mbr_lim_jac_m23.pred --reward jaccard
mbr_lim.py --universe experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred --lims experiments/prediction_files/fce/max_vote1.pred experiments/prediction_files/fce/max_vote3.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/fce/mbr_lim_rec_m13.pred --reward rec
mbr_lim.py --universe experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred --lims experiments/prediction_files/fce/max_vote2.pred experiments/prediction_files/fce/max_vote3.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/fce/mbr_lim_rec_m23.pred --reward rec
mbr_lim.py --universe experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred --lims experiments/prediction_files/fce/max_vote1.pred experiments/prediction_files/fce/max_vote3.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/fce/mbr_lim_prec_m13.pred --reward prec
mbr_lim.py --universe experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred --lims experiments/prediction_files/fce/max_vote2.pred experiments/prediction_files/fce/max_vote3.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/fce/mbr_lim_prec_m23.pred --reward prec
mbr_lim.py --universe experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred --lims experiments/prediction_files/fce/max_vote1.pred experiments/prediction_files/fce/max_vote3.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/fce/mbr_lim_f05_m13.pred --reward f05
mbr_lim.py --universe experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred --lims experiments/prediction_files/fce/max_vote2.pred experiments/prediction_files/fce/max_vote3.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/fce/mbr_lim_f05_m23.pred --reward f05
mbr_lim.py --universe experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred --lims experiments/prediction_files/fce/max_vote1.pred experiments/prediction_files/fce/max_vote3.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/fce/mbr_lim_jac_m13.pred --reward jaccard
mbr_lim.py --universe experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred --lims experiments/prediction_files/fce/max_vote2.pred experiments/prediction_files/fce/max_vote3.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/fce/mbr_lim_jac_m23.pred --reward jaccard
mbr_lim.py --lims experiments/prediction_files/Linguaskill_test_comb/max_vote_4.pred experiments/prediction_files/Linguaskill_test_comb/max_vote_5.pred experiments/prediction_files/Linguaskill_test_comb/max_vote_6.pred experiments/prediction_files/Linguaskill_test/bert.pred experiments/prediction_files/Linguaskill_test/roberta.pred experiments/prediction_files/Linguaskill_test/xlnet.pred --universe experiments/prediction_files/Linguaskill_test_FineTuned/bert.pred experiments/prediction_files/Linguaskill_test_FineTuned/roberta.pred experiments/prediction_files/Linguaskill_test_FineTuned/xlnet.pred --input ../data/Linguaskill/preprocessed/ls_test.inc --reward prec --outfile experiments/prediction_files/Linguaskill_test_comb/mbr_p_vote_456_uFT
mbr_lim.py --lims experiments/prediction_files/Linguaskill_test_comb/max_vote_4.pred experiments/prediction_files/Linguaskill_test_comb/max_vote_5.pred experiments/prediction_files/Linguaskill_test_comb/max_vote_6.pred experiments/prediction_files/Linguaskill_test/bert.pred experiments/prediction_files/Linguaskill_test/roberta.pred experiments/prediction_files/Linguaskill_test/xlnet.pred --universe experiments/prediction_files/Linguaskill_test_FineTuned/bert.pred experiments/prediction_files/Linguaskill_test_FineTuned/roberta.pred experiments/prediction_files/Linguaskill_test_FineTuned/xlnet.pred --input ../data/Linguaskill/preprocessed/ls_test.inc --reward prec --outfile experiments/prediction_files/Linguaskill_test_comb/mbr_p_vote_456_uFT
mbr_lim.py --lims experiments/prediction_files/Linguaskill_test_comb/max_vote_4.pred experiments/prediction_files/Linguaskill_test_comb/max_vote_5.pred experiments/prediction_files/Linguaskill_test_comb/max_vote_6.pred experiments/prediction_files/Linguaskill_test/bert.pred experiments/prediction_files/Linguaskill_test/roberta.pred experiments/prediction_files/Linguaskill_test/xlnet.pred --universe experiments/prediction_files/Linguaskill_test_FineTuned/bert.pred experiments/prediction_files/Linguaskill_test_FineTuned/roberta.pred experiments/prediction_files/Linguaskill_test_FineTuned/xlnet.pred --input ../data/Linguaskill/preprocessed/ls_test.inc --reward f05 --outfile experiments/prediction_files/Linguaskill_test_comb/mbr_f05_vote_456_uFT
mbr_lim.py --lims experiments/prediction_files/Linguaskill_test_comb/max_vote_4.pred experiments/prediction_files/Linguaskill_test_comb/max_vote_5.pred experiments/prediction_files/Linguaskill_test_comb/max_vote_6.pred experiments/prediction_files/Linguaskill_test/bert.pred experiments/prediction_files/Linguaskill_test/roberta.pred experiments/prediction_files/Linguaskill_test/xlnet.pred --universe experiments/prediction_files/Linguaskill_test_FineTuned/bert.pred experiments/prediction_files/Linguaskill_test_FineTuned/roberta.pred experiments/prediction_files/Linguaskill_test_FineTuned/xlnet.pred --input ../data/Linguaskill/preprocessed/ls_test.inc --reward f05 --outfile experiments/prediction_files/Linguaskill_test_comb/mbr_f05_vote_456_uFT
