mbr_diff.py --selection experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred --universe experiments/prediction_files/conll/max_vote2.pred experiments/prediction_files/conll/max_vote3.pred --input ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --outfile experiments/prediction_files/conll/prec.pred --reward prec
mbr_diff.py --selection experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred --universe experiments/prediction_files/conll/max_vote2.pred experiments/prediction_files/conll/max_vote3.pred --input ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --outfile experiments/prediction_files/conll/prec.pred --reward prec
mbr_diff.py --selection experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred --universe experiments/prediction_files/conll/max_vote2.pred experiments/prediction_files/conll/max_vote3.pred --input ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --outfile experiments/prediction_files/conll/f05.pred --reward f05
mbr_diff.py --selection experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred --universe experiments/prediction_files/conll/max_vote2.pred experiments/prediction_files/conll/max_vote3.pred --input ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --outfile experiments/prediction_files/conll/jac.pred --reward jaccard
mbr_diff.py --universe experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred --selection experiments/prediction_files/conll/max_vote2.pred experiments/prediction_files/conll/max_vote3.pred --input ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --outfile experiments/prediction_files/conll/f05.pred --reward f05
mbr_diff.py --universe experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred --selection experiments/prediction_files/conll/max_vote2.pred experiments/prediction_files/conll/max_vote3.pred --input ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --outfile experiments/prediction_files/conll/prec.pred --reward prec
mbr_diff.py --universe experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred --selection experiments/prediction_files/conll/max_vote2.pred experiments/prediction_files/conll/max_vote3.pred --input ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --outfile experiments/prediction_files/conll/jac.pred --reward jaccard
mbr_diff.py --universe experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred experiments/prediction_files/conll/max_vote2.pred experiments/prediction_files/conll/max_vote3.pred --selection experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred --input ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --outfile experiments/prediction_files/conll/jac.pred --reward jaccard
mbr_diff.py --universe experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred experiments/prediction_files/conll/max_vote2.pred experiments/prediction_files/conll/max_vote3.pred --selection experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred --input ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --outfile experiments/prediction_files/conll/f05.pred --reward f05
mbr_diff.py --universe experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred experiments/prediction_files/conll/max_vote2.pred experiments/prediction_files/conll/max_vote3.pred --selection experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred --input ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --outfile experiments/prediction_files/conll/prec.pred --reward prec
mbr_diff.py --universe experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred --selection experiments/prediction_files/fce/max_vote2.pred experiments/prediction_files/fce/max_vote3.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/fce/f05.pred --reward f05
mbr_diff.py --universe experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred --selection experiments/prediction_files/fce/max_vote2.pred experiments/prediction_files/fce/max_vote3.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/fce/jac.pred --reward jaccard
mbr_diff.py --universe experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred --selection experiments/prediction_files/fce/max_vote2.pred experiments/prediction_files/fce/max_vote3.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/fce/prec.pred --reward prec
mbr_diff.py --universe experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred experiments/prediction_files/fce/max_vote2.pred experiments/prediction_files/fce/max_vote3.pred --selection experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/fce/prec.pred --reward prec
mbr_diff.py --universe experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred experiments/prediction_files/fce/max_vote2.pred experiments/prediction_files/fce/max_vote3.pred --selection experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/fce/f05.pred --reward f05
mbr_diff.py --universe experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred experiments/prediction_files/fce/max_vote2.pred experiments/prediction_files/fce/max_vote3.pred --selection experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/fce/jac.pred --reward jaccard
mbr_diff.py --universe experiments/prediction_files/bea/bert.pred experiments/prediction_files/bea/roberta.pred experiments/prediction_files/bea/xlnet.pred --selection experiments/prediction_files/bea/max_vote2.pred experiments/prediction_files/bea/max_vote3.pred --input ../data/BEA2019/bea2019test.txt --outfile experiments/prediction_files/bea/prec.pred --reward prec
mbr_diff.py --universe experiments/prediction_files/bea/bert.pred experiments/prediction_files/bea/roberta.pred experiments/prediction_files/bea/xlnet.pred --selection experiments/prediction_files/bea/max_vote2.pred experiments/prediction_files/bea/max_vote3.pred --input ../data/BEA2019/bea2019test.txt --outfile experiments/prediction_files/bea/f05.pred --reward f05
mbr_diff.py --universe experiments/prediction_files/bea/bert.pred experiments/prediction_files/bea/roberta.pred experiments/prediction_files/bea/xlnet.pred --selection experiments/prediction_files/bea/max_vote2.pred experiments/prediction_files/bea/max_vote3.pred --input ../data/BEA2019/bea2019test.txt --outfile experiments/prediction_files/bea/jac.pred --reward jaccard
mbr_diff.py --universe experiments/prediction_files/bea/bert.pred experiments/prediction_files/bea/roberta.pred experiments/prediction_files/bea/xlnet.pred experiments/prediction_files/bea/max_vote2.pred experiments/prediction_files/bea/max_vote3.pred --selection experiments/prediction_files/bea/bert.pred experiments/prediction_files/bea/roberta.pred experiments/prediction_files/bea/xlnet.pred --input ../data/BEA2019/bea2019test.txt --outfile experiments/prediction_files/bea/prec.pred --reward prec
mbr_diff.py --universe experiments/prediction_files/bea/bert.pred experiments/prediction_files/bea/roberta.pred experiments/prediction_files/bea/xlnet.pred experiments/prediction_files/bea/max_vote2.pred experiments/prediction_files/bea/max_vote3.pred --selection experiments/prediction_files/bea/bert.pred experiments/prediction_files/bea/roberta.pred experiments/prediction_files/bea/xlnet.pred --input ../data/BEA2019/bea2019test.txt --outfile experiments/prediction_files/bea/f05.pred --reward f05
mbr_diff.py --universe experiments/prediction_files/bea/bert.pred experiments/prediction_files/bea/roberta.pred experiments/prediction_files/bea/xlnet.pred experiments/prediction_files/bea/max_vote2.pred experiments/prediction_files/bea/max_vote3.pred --selection experiments/prediction_files/bea/bert.pred experiments/prediction_files/bea/roberta.pred experiments/prediction_files/bea/xlnet.pred --input ../data/BEA2019/bea2019test.txt --outfile experiments/prediction_files/bea/jac.pred --reward jaccard
mbr_diff.py --universe experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred --selection experiments/prediction_files/conll/max_vote1.pred experiments/prediction_files/conll/max_vote2.pred experiments/prediction_files/conll/max_vote3.pred --input ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --outfile experiments/prediction_files/conll/jac.pred --reward jaccard
mbr_diff.py --universe experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred --selection experiments/prediction_files/conll/max_vote1.pred experiments/prediction_files/conll/max_vote2.pred experiments/prediction_files/conll/max_vote3.pred --input ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --outfile experiments/prediction_files/conll/f05.pred --reward f05
mbr_diff.py --universe experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred --selection experiments/prediction_files/conll/max_vote1.pred experiments/prediction_files/conll/max_vote2.pred experiments/prediction_files/conll/max_vote3.pred --input ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --outfile experiments/prediction_files/conll/prec.pred --reward prec
mbr_diff.py --universe experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred --selection experiments/prediction_files/conll/max_vote1.pred experiments/prediction_files/conll/max_vote2.pred experiments/prediction_files/conll/max_vote3.pred --input ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --outfile experiments/prediction_files/conll/rec.pred --reward rec
mbr_diff.py --universe experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred --selection experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred experiments/prediction_files/conll/max_vote1.pred experiments/prediction_files/conll/max_vote2.pred experiments/prediction_files/conll/max_vote3.pred --input ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --outfile experiments/prediction_files/conll/rec.pred --reward rec
mbr_diff.py --universe experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred --selection experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred experiments/prediction_files/conll/max_vote1.pred experiments/prediction_files/conll/max_vote2.pred experiments/prediction_files/conll/max_vote3.pred --input ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --outfile experiments/prediction_files/conll/prec.pred --reward prec
mbr_diff.py --universe experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred --selection experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred experiments/prediction_files/conll/max_vote1.pred experiments/prediction_files/conll/max_vote2.pred experiments/prediction_files/conll/max_vote3.pred --input ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --outfile experiments/prediction_files/conll/f05.pred --reward f05
mbr_diff.py --universe experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred --selection experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred experiments/prediction_files/conll/max_vote1.pred experiments/prediction_files/conll/max_vote2.pred experiments/prediction_files/conll/max_vote3.pred --input ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --outfile experiments/prediction_files/conll/jac.pred --reward jaccard
mbr_diff.py --universe experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred --selection experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred experiments/prediction_files/conll/max_vote2.pred experiments/prediction_files/conll/max_vote3.pred --input ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --outfile experiments/prediction_files/conll/rec.pred --reward rec
mbr_diff.py --universe experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred --selection experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred experiments/prediction_files/conll/max_vote2.pred experiments/prediction_files/conll/max_vote3.pred --input ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --outfile experiments/prediction_files/conll/prec.pred --reward prec
mbr_diff.py --universe experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred --selection experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred experiments/prediction_files/conll/max_vote2.pred experiments/prediction_files/conll/max_vote3.pred --input ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --outfile experiments/prediction_files/conll/f05.pred --reward f05
mbr_diff.py --universe experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred --selection experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred experiments/prediction_files/conll/max_vote2.pred experiments/prediction_files/conll/max_vote3.pred --input ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --outfile experiments/prediction_files/conll/jac.pred --reward jaccard
mbr_diff.py --universe experiments/prediction_files/conll/bert.pred experiments/prediction_files/conll/roberta.pred experiments/prediction_files/conll/xlnet.pred --selection experiments/prediction_files/conll/max_vote2.pred experiments/prediction_files/conll/max_vote3.pred --input ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --outfile experiments/prediction_files/conll/rec.pred --reward rec
mbr_diff.py --universe experiments/prediction_files/bea/bert.pred experiments/prediction_files/bea/roberta.pred experiments/prediction_files/bea/xlnet.pred --selection experiments/prediction_files/bea/max_vote1.pred experiments/prediction_files/bea/max_vote2.pred experiments/prediction_files/bea/max_vote3.pred --input ../data/BEA2019/bea2019test.txt --outfile experiments/prediction_files/bea/mbr_diff_rec_m123.pred --reward rec
mbr_diff.py --universe experiments/prediction_files/bea/bert.pred experiments/prediction_files/bea/roberta.pred experiments/prediction_files/bea/xlnet.pred --selection experiments/prediction_files/bea/max_vote2.pred experiments/prediction_files/bea/max_vote3.pred --input ../data/BEA2019/bea2019test.txt --outfile experiments/prediction_files/bea/mbr_diff_rec_m23.pred --reward rec
mbr_diff.py --universe experiments/prediction_files/bea/bert.pred experiments/prediction_files/bea/roberta.pred experiments/prediction_files/bea/xlnet.pred --selection experiments/prediction_files/bea/bert.pred experiments/prediction_files/bea/roberta.pred experiments/prediction_files/bea/xlnet.pred experiments/prediction_files/bea/max_vote1.pred experiments/prediction_files/bea/max_vote2.pred experiments/prediction_files/bea/max_vote3.pred --input ../data/BEA2019/bea2019test.txt --outfile experiments/prediction_files/bea/mbr_diff_rec_brx_m123.pred --reward rec
mbr_diff.py --universe experiments/prediction_files/bea/bert.pred experiments/prediction_files/bea/roberta.pred experiments/prediction_files/bea/xlnet.pred --selection experiments/prediction_files/bea/bert.pred experiments/prediction_files/bea/roberta.pred experiments/prediction_files/bea/xlnet.pred experiments/prediction_files/bea/max_vote2.pred experiments/prediction_files/bea/max_vote3.pred --input ../data/BEA2019/bea2019test.txt --outfile experiments/prediction_files/bea/mbr_diff_rec_brx_m23.pred --reward rec
mbr_diff.py --universe experiments/prediction_files/bea/bert.pred experiments/prediction_files/bea/roberta.pred experiments/prediction_files/bea/xlnet.pred --selection experiments/prediction_files/bea/max_vote1.pred experiments/prediction_files/bea/max_vote2.pred experiments/prediction_files/bea/max_vote3.pred --input ../data/BEA2019/bea2019test.txt --outfile experiments/prediction_files/bea/mbr_diff_prec_m123.pred --reward prec
mbr_diff.py --universe experiments/prediction_files/bea/bert.pred experiments/prediction_files/bea/roberta.pred experiments/prediction_files/bea/xlnet.pred --selection experiments/prediction_files/bea/max_vote2.pred experiments/prediction_files/bea/max_vote3.pred --input ../data/BEA2019/bea2019test.txt --outfile experiments/prediction_files/bea/mbr_diff_prec_m23.pred --reward prec
mbr_diff.py --universe experiments/prediction_files/bea/bert.pred experiments/prediction_files/bea/roberta.pred experiments/prediction_files/bea/xlnet.pred --selection experiments/prediction_files/bea/bert.pred experiments/prediction_files/bea/roberta.pred experiments/prediction_files/bea/xlnet.pred experiments/prediction_files/bea/max_vote1.pred experiments/prediction_files/bea/max_vote2.pred experiments/prediction_files/bea/max_vote3.pred --input ../data/BEA2019/bea2019test.txt --outfile experiments/prediction_files/bea/mbr_diff_prec_brx_m123.pred --reward prec
mbr_diff.py --universe experiments/prediction_files/bea/bert.pred experiments/prediction_files/bea/roberta.pred experiments/prediction_files/bea/xlnet.pred --selection experiments/prediction_files/bea/bert.pred experiments/prediction_files/bea/roberta.pred experiments/prediction_files/bea/xlnet.pred experiments/prediction_files/bea/max_vote2.pred experiments/prediction_files/bea/max_vote3.pred --input ../data/BEA2019/bea2019test.txt --outfile experiments/prediction_files/bea/mbr_diff_prec_brx_m23.pred --reward prec
mbr_diff.py --universe experiments/prediction_files/bea/bert.pred experiments/prediction_files/bea/roberta.pred experiments/prediction_files/bea/xlnet.pred --selection experiments/prediction_files/bea/max_vote1.pred experiments/prediction_files/bea/max_vote2.pred experiments/prediction_files/bea/max_vote3.pred --input ../data/BEA2019/bea2019test.txt --outfile experiments/prediction_files/bea/mbr_diff_f05_m123.pred --reward f05
mbr_diff.py --universe experiments/prediction_files/bea/bert.pred experiments/prediction_files/bea/roberta.pred experiments/prediction_files/bea/xlnet.pred --selection experiments/prediction_files/bea/max_vote2.pred experiments/prediction_files/bea/max_vote3.pred --input ../data/BEA2019/bea2019test.txt --outfile experiments/prediction_files/bea/mbr_diff_f05_m23.pred --reward f05
mbr_diff.py --universe experiments/prediction_files/bea/bert.pred experiments/prediction_files/bea/roberta.pred experiments/prediction_files/bea/xlnet.pred --selection experiments/prediction_files/bea/bert.pred experiments/prediction_files/bea/roberta.pred experiments/prediction_files/bea/xlnet.pred experiments/prediction_files/bea/max_vote1.pred experiments/prediction_files/bea/max_vote2.pred experiments/prediction_files/bea/max_vote3.pred --input ../data/BEA2019/bea2019test.txt --outfile experiments/prediction_files/bea/mbr_diff_f05_brx_m123.pred --reward f05
mbr_diff.py --universe experiments/prediction_files/bea/bert.pred experiments/prediction_files/bea/roberta.pred experiments/prediction_files/bea/xlnet.pred --selection experiments/prediction_files/bea/bert.pred experiments/prediction_files/bea/roberta.pred experiments/prediction_files/bea/xlnet.pred experiments/prediction_files/bea/max_vote2.pred experiments/prediction_files/bea/max_vote3.pred --input ../data/BEA2019/bea2019test.txt --outfile experiments/prediction_files/bea/mbr_diff_f05_brx_m23.pred --reward f05
mbr_diff.py --universe experiments/prediction_files/bea/bert.pred experiments/prediction_files/bea/roberta.pred experiments/prediction_files/bea/xlnet.pred --selection experiments/prediction_files/bea/max_vote1.pred experiments/prediction_files/bea/max_vote2.pred experiments/prediction_files/bea/max_vote3.pred --input ../data/BEA2019/bea2019test.txt --outfile experiments/prediction_files/bea/mbr_diff_jac_m123.pred --reward jaccard
mbr_diff.py --universe experiments/prediction_files/bea/bert.pred experiments/prediction_files/bea/roberta.pred experiments/prediction_files/bea/xlnet.pred --selection experiments/prediction_files/bea/max_vote2.pred experiments/prediction_files/bea/max_vote3.pred --input ../data/BEA2019/bea2019test.txt --outfile experiments/prediction_files/bea/mbr_diff_jac_m23.pred --reward jaccard
mbr_diff.py --universe experiments/prediction_files/bea/bert.pred experiments/prediction_files/bea/roberta.pred experiments/prediction_files/bea/xlnet.pred --selection experiments/prediction_files/bea/bert.pred experiments/prediction_files/bea/roberta.pred experiments/prediction_files/bea/xlnet.pred experiments/prediction_files/bea/max_vote1.pred experiments/prediction_files/bea/max_vote2.pred experiments/prediction_files/bea/max_vote3.pred --input ../data/BEA2019/bea2019test.txt --outfile experiments/prediction_files/bea/mbr_diff_jac_brx_m123.pred --reward jaccard
mbr_diff.py --universe experiments/prediction_files/bea/bert.pred experiments/prediction_files/bea/roberta.pred experiments/prediction_files/bea/xlnet.pred --selection experiments/prediction_files/bea/bert.pred experiments/prediction_files/bea/roberta.pred experiments/prediction_files/bea/xlnet.pred experiments/prediction_files/bea/max_vote2.pred experiments/prediction_files/bea/max_vote3.pred --input ../data/BEA2019/bea2019test.txt --outfile experiments/prediction_files/bea/mbr_diff_jac_brx_m23.pred --reward jaccard
mbr_diff.py --universe experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred --selection experiments/prediction_files/fce/max_vote1.pred experiments/prediction_files/fce/max_vote2.pred experiments/prediction_files/fce/max_vote3.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/fce/mbr_diff_rec_m123.pred --reward rec
mbr_diff.py --universe experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred --selection experiments/prediction_files/fce/max_vote2.pred experiments/prediction_files/fce/max_vote3.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/fce/mbr_diff_rec_m23.pred --reward rec
mbr_diff.py --universe experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred --selection experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred experiments/prediction_files/fce/max_vote1.pred experiments/prediction_files/fce/max_vote2.pred experiments/prediction_files/fce/max_vote3.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/fce/mbr_diff_rec_brx_m123.pred --reward rec
mbr_diff.py --universe experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred --selection experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred experiments/prediction_files/fce/max_vote2.pred experiments/prediction_files/fce/max_vote3.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/fce/mbr_diff_rec_brx_m23.pred --reward rec
mbr_diff.py --universe experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred --selection experiments/prediction_files/fce/max_vote1.pred experiments/prediction_files/fce/max_vote2.pred experiments/prediction_files/fce/max_vote3.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/fce/mbr_diff_prec_m123.pred --reward prec
mbr_diff.py --universe experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred --selection experiments/prediction_files/fce/max_vote2.pred experiments/prediction_files/fce/max_vote3.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/fce/mbr_diff_prec_m23.pred --reward prec
mbr_diff.py --universe experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred --selection experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred experiments/prediction_files/fce/max_vote1.pred experiments/prediction_files/fce/max_vote2.pred experiments/prediction_files/fce/max_vote3.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/fce/mbr_diff_prec_brx_m123.pred --reward prec
mbr_diff.py --universe experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred --selection experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred experiments/prediction_files/fce/max_vote2.pred experiments/prediction_files/fce/max_vote3.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/fce/mbr_diff_prec_brx_m23.pred --reward prec
mbr_diff.py --universe experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred --selection experiments/prediction_files/fce/max_vote1.pred experiments/prediction_files/fce/max_vote2.pred experiments/prediction_files/fce/max_vote3.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/fce/mbr_diff_f05_m123.pred --reward f05
mbr_diff.py --universe experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred --selection experiments/prediction_files/fce/max_vote2.pred experiments/prediction_files/fce/max_vote3.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/fce/mbr_diff_f05_m23.pred --reward f05
mbr_diff.py --universe experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred --selection experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred experiments/prediction_files/fce/max_vote1.pred experiments/prediction_files/fce/max_vote2.pred experiments/prediction_files/fce/max_vote3.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/fce/mbr_diff_f05_brx_m123.pred --reward f05
mbr_diff.py --universe experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred --selection experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred experiments/prediction_files/fce/max_vote2.pred experiments/prediction_files/fce/max_vote3.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/fce/mbr_diff_f05_brx_m23.pred --reward f05
mbr_diff.py --universe experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred --selection experiments/prediction_files/fce/max_vote1.pred experiments/prediction_files/fce/max_vote2.pred experiments/prediction_files/fce/max_vote3.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/fce/mbr_diff_jac_m123.pred --reward jaccard
mbr_diff.py --universe experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred --selection experiments/prediction_files/fce/max_vote2.pred experiments/prediction_files/fce/max_vote3.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/fce/mbr_diff_jac_m23.pred --reward jaccard
mbr_diff.py --universe experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred --selection experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred experiments/prediction_files/fce/max_vote1.pred experiments/prediction_files/fce/max_vote2.pred experiments/prediction_files/fce/max_vote3.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/fce/mbr_diff_jac_brx_m123.pred --reward jaccard
mbr_diff.py --universe experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred --selection experiments/prediction_files/fce/bert.pred experiments/prediction_files/fce/roberta.pred experiments/prediction_files/fce/xlnet.pred experiments/prediction_files/fce/max_vote2.pred experiments/prediction_files/fce/max_vote3.pred --input /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --outfile experiments/prediction_files/fce/mbr_diff_jac_brx_m23.pred --reward jaccard
