predict.py --model_path experiments/trained_models/bert_0_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_file experiments/prediction_files/conll/bert.pred --transformer_model bert
predict.py --model_path experiments/trained_models/bert_0_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_file experiments/prediction_files/conll/bert.pred --transformer_model bert
predict.py --model_path experiments/trained_models/bert_0_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_file experiments/prediction_files/conll/bert.pred --transformer_model bert --special_tokens_fix 0
predict.py --model_path experiments/trained_models/xlnet_0_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_file experiments/prediction_files/conll/xlnet.pred --transformer_model xlnet --special_tokens_fix 0
predict.py --model_path experiments/trained_models/roberta_1_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_file experiments/prediction_files/conll/roberta.pred --transformer_model roberta
predict.py --model_path experiments/trained_models/roberta_1_gectorv2.th --vocab_path data/output_vocabulary --input_file /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --output_file experiments/prediction_files/fce/roberta.pred --transformer_model roberta
predict.py --model_path experiments/trained_models/xlnet_0_gectorv2.th --vocab_path data/output_vocabulary --input_file /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --output_file experiments/prediction_files/fce/xlnet.pred --transformer_model xlnet --special_tokens_fix 0
predict.py --model_path experiments/trained_models/bert_0_gectorv2.th --vocab_path data/output_vocabulary --input_file /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --output_file experiments/prediction_files/fce/bert.pred --transformer_model bert --special_tokens_fix 0
predict.py --model_path experiments/trained_models/bert_0_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/BEA2019/bea2019test.txt --output_file experiments/prediction_files/bea/bert.pred --transformer_model bert --special_tokens_fix 0
predict.py --model_path experiments/trained_models/xlnet_0_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/BEA2019/bea2019test.txt --output_file experiments/prediction_files/bea/xlnet.pred --transformer_model xlnet --special_tokens_fix 0
predict.py --model_path experiments/trained_models/roberta_1_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/BEA2019/bea2019test.txt --output_file experiments/prediction_files/bea/roberta.pred --transformer_model roberta
predict.py --model_path experiments/trained_models/xlnet_0_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/ELIT/input.txt --output_file experiments/prediction_files/elit/xlnet.pred --transformer_model xlnet --special_tokens_fix 0
predict.py --model_path experiments/trained_models/xlnet_0_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/ELIT/input.txt --output_file experiments/prediction_files/elit/xlnet.pred --transformer_model xlnet --special_tokens_fix 0 --batch_size 16
predict.py --model_path experiments/trained_models/xlnet_0_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/ELIT/input.txt --output_file experiments/prediction_files/elit/xlnet.pred --transformer_model xlnet --special_tokens_fix 0 --batch_size 16
predict.py --model_path experiments/trained_models/xlnet_0_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/ELIT/input.txt --output_file experiments/prediction_files/elit/bert.pred --transformer_model bert --special_tokens_fix 0 --batch_size 16
predict.py --model_path experiments/trained_models/bert_0_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/ELIT/input.txt --output_file experiments/prediction_files/elit/bert.pred --transformer_model bert --special_tokens_fix 0 --batch_size 16
predict.py --model_path experiments/trained_models/roberta_0_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/ELIT/input.txt --output_file experiments/prediction_files/elit/roberta.pred --transformer_model roberta --batch_size 16
predict.py --model_path experiments/trained_models/roberta_1_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/ELIT/input.txt --output_file experiments/prediction_files/elit/roberta.pred --transformer_model roberta --batch_size 16
predict.py --model_path experiments/trained_models/bert_0_gectorv2.th --vocab_path data/output_vocabulary --input_file /home/alta/CLC/LNRC/exams/FCEsplit-public/v3/fce-public.test.inc --output_file experiments/prediction_files/fce/bert.pred --transformer_model bert --special_tokens_fix 0
predict.py --model_path experiments/trained_models/xlnet_0_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/ELIT/input.txt --output_file experiments/prediction_files/elit/xlnet.pred --transformer_model xlnet --special_tokens_fix 0
predict.py --model_path experiments/trained_models/bert_0_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_file experiments/prediction_files/conll/bert.pred --transformer_model bert --special_tokens_fix 0
predict.py --model_path experiments/trained_models/bert_0_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_file experiments/prediction_files/conll/bert.pred --transformer_model bert --special_tokens_fix 0
predict.py --model_path experiments/trained_models/bert_0_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_file experiments/prediction_files/conll/bert_th624.pred --transformer_model bert --special_tokens_fix 0
predict.py --model_path experiments/trained_models/xlnet_0_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_file experiments/prediction_files/conll/xlnet.pred --transformer_model xlnet --special_tokens_fix 0predict.py --model_path ../trained_models/bert_0_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_file experiments/prediction_files/conll/bert2.pred --transformer_model bert --special_tokens_fix 0
predict.py --model_path ../trained_models/bert_0_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/CoNLL-14/conll14st-test-data/noalt/input_sentences.txt --output_file experiments/prediction_files/conll/bert.pred --transformer_model bert --special_tokens_fix 0
predict.py --model_path ../trained_models/bert_0_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/FCE/fce-public.test.inc --output_file experiments/prediction_files/FCE --transformer_model bert --special_tokens_fix 0
predict.py --model_path ../trained_models/bert_0_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/FCE/fce-public.test.inc --output_file experiments/prediction_files/FCE/bert.pred --transformer_model bert --special_tokens_fix 0
predict.py --model_path ../trained_models/bert_0_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/FCE/fce-public.test.inc --output_file experiments/prediction_files/FCE/bert.pred --transformer_model bert --special_tokens_fix 0
predict.py --model_path ../trained_models/bert_0_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/FCE/fce-public.test.inc --output_file experiments/prediction_files/FCE/bert.pred --transformer_model bert --iteration_count 3
predict.py --model_path ../trained_models/bert_0_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/FCE/fce-public.test.inc --output_file experiments/prediction_files/FCE/bert.pred --transformer_model bert --iteration_count 1
predict.py --model_path ../trained_models/bert_0_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/FCE/fce-public.test.inc --output_file experiments/prediction_files/FCE/bert.pred --transformer_model bert --iteration_count 1
predict.py --model_path ../trained_models/bert_0_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/FCE/fce-public.test.inc --output_file experiments/prediction_files/FCE/bert.pred --transformer_model bert --special_tokens_fix 0 --iteration_count 1
predict.py --model_path ../trained_models/bert_0_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/FCE/fce-public.test.inc --output_file experiments/prediction_files/FCE/bert.pred --transformer_model bert --special_tokens_fix 0 --iteration_count 3
predict.py --model_path ../trained_models/bert_0_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/FCE/fce-public.test.inc --output_file experiments/prediction_files/FCE/bert.pred --transformer_model bert --special_tokens_fix 0 --iteration_count 1
predict.py --model_path ../trained_models/xlnet_0_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/FCE/fce-public.test.inc --output_file experiments/prediction_files/FCE/xlnet.pred --transformer_model xlnet --special_tokens_fix 0 --iteration_count 1
predict.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/FCE/fce-public.test.inc --output_file experiments/prediction_files/FCE/xlnet.pred --transformer_model xlnet --special_tokens_fix 0 --is_ensemble 1 --iteration_count 1
predict.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/FCE/fce-public.test.inc --output_file experiments/prediction_files/FCE/ensemble.pred --transformer_model xlnet --special_tokens_fix 0 --is_ensemble 1 --iteration_count 1
predict.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/prediction_files/Linguaskill_test/ensemble.pred --transformer_model xlnet --special_tokens_fix 0 --is_ensemble 1 --iteration_count 1
predict.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/prediction_files/Linguaskill_test/ensemble.pred --transformer_model xlnet --special_tokens_fix 0 --is_ensemble 1 --iteration_count 1
predict.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test_lc.inc --output_file experiments/prediction_files/Linguaskill_test/lc_ensemble.pred --transformer_model xlnet --special_tokens_fix 0 --is_ensemble 1 --iteration_count 1
predict.py --model_path ../trained_models/xlnet_0_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/prediction_files/Linguaskill_test/xlnet.pred --transformer_model xlnet --special_tokens_fix 0 --iteration_count 1
predict.py --model_path ../trained_models/roberta_1_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/prediction_files/Linguaskill_test/roberta.pred --transformer_model roberta --special_tokens_fix 1 --iteration_count 1
predict.py --model_path ../trained_models/bert_0_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/prediction_files/Linguaskill_test/bert.pred --transformer_model bert --special_tokens_fix 0 --iteration_count 1
predict.py --model_path ../trained_models/xlnet_0_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/prediction_files/Linguaskill_test/xlnet_ens.pred --transformer_model xlnet --special_tokens_fix 0 --is_ensemble 1 --iteration_count 1
predict.py --model_path ../trained_models/xlnet_0_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/prediction_files/Linguaskill_test/xlnet_stf.pred --transformer_model xlnet --special_tokens_fix 1 --iteration_count 1
predict.py --model_path ../trained_models/xlnet_0_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/FCE/fce-public.test.inc --output_file experiments/prediction_files/FCE/xlnet.pred --transformer_model xlnet --special_tokens_fix 0 --iteration_count 1
predict.py --model_path ../trained_models/roberta_1_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/FCE/fce-public.test.inc --output_file experiments/prediction_files/FCE/roberta.pred --transformer_model roberta --special_tokens_fix 1 --iteration_count 1
predict.py --model_path ../trained_models/roberta_1_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/FCE/fce-public.test.inc --output_file experiments/prediction_files/FCE/roberta.pred --transformer_model roberta --special_tokens_fix 1 --iteration_count 1
predict.py --model_path ../trained_models/roberta_1_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/FCE/fce-public.test.inc --output_file experiments/prediction_files/FCE/roberta.pred --transformer_model roberta --special_tokens_fix 1 --iteration_count 1
predict.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/FCE/fce-public.test.inc --output_file experiments/prediction_files/FCE/ensemble_b.pred --transformer_model bert --special_tokens_fix 0 --is_ensemble 1 --iteration_count 1
predict.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/FCE/fce-public.test.inc --output_file experiments/prediction_files/FCE/ensemble_xl.pred --transformer_model xlnet --special_tokens_fix 0 --is_ensemble 1 --iteration_count 1

predict.py --model_path ../trained_models/bert_0_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/prediction_files/Linguaskill_test/bert.pred --transformer_model bert --special_tokens_fix 0 --iteration_count 1
predict.py --model_path ../trained_models/bert_0_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/prediction_files/Linguaskill_test/bert.pred --transformer_model bert --special_tokens_fix 0 --iteration_count 1
predict.py --model_path ../trained_models/bert_0_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/prediction_files/Linguaskill_test/bert.pred --transformer_model bert --special_tokens_fix 0 --iteration_count 1 --speech 1
predict.py --model_path ../trained_models/bert_0_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/prediction_files/Linguaskill_test/bert.pred --transformer_model bert --special_tokens_fix 0 --iteration_count 1 --speech 1
predict.py --model_path ../trained_models/roberta_1_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/prediction_files/Linguaskill_test/roberta.pred --transformer_model roberta --special_tokens_fix 1 --iteration_count 1
predict.py --model_path ../trained_models/xlnet_0_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/prediction_files/Linguaskill_test/xlnet.pred --transformer_model xlnet --special_tokens_fix 0 --iteration_count 1 --speech 1
predict.py --model_path ../trained_models/roberta_1_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/prediction_files/Linguaskill_test/roberta.pred --transformer_model roberta --special_tokens_fix 1 --iteration_count 1 --speech 1
predict.py --model_path ../trained_models/xlnet_0_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/prediction_files/Linguaskill_test/xlnet.pred --transformer_model xlnet --special_tokens_fix 0 --iteration_count 1 --speech 1
predict.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/prediction_files/Linguaskill_test/ensemble.pred --transformer_model xlnet --special_tokens_fix 0 --is_ensemble 1 --iteration_count 1 --speech 1
predict.py --model_path ../trained_models/best.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/prediction_files/Linguaskill_test/roberta.pred --transformer_model roberta --special_tokens_fix 1 --iteration_count 1 --speech 1
predict.py --model_path ../trained_models/best.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/prediction_files/Linguaskill_test_FineTuned/roberta.pred --transformer_model roberta --special_tokens_fix 1 --iteration_count 1 --speech 1
predict.py --model_path ../trained_models/roberta_1_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/prediction_files/Linguaskill_test/roberta.pred --transformer_model roberta --special_tokens_fix 1 --iteration_count 1 --speech 1
predict.py --model_path ../trained_models/best.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/prediction_files/Linguaskill_test_FineTuned/roberta_ns.pred --transformer_model roberta --special_tokens_fix 1 --iteration_count 1 --speech 0
predict.py --model_path ../trained_models/roberta_1_gectorv2finetuned2.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/prediction_files/Linguaskill_test_FineTuned/roberta.pred --transformer_model roberta --special_tokens_fix 1 --iteration_count 1 --speech 1
predict.py --model_path ../trained_models/roberta_1_gectorv2finetuned2.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/prediction_files/Linguaskill_test_FineTuned/roberta.pred --transformer_model roberta --special_tokens_fix 1 --iteration_count 1 --speech 1
predict.py --model_path ../trained_models/roberta_1_gectorv2finetuned.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/prediction_files/Linguaskill_test_FineTuned/roberta.pred --transformer_model roberta --special_tokens_fix 1 --iteration_count 1 --speech 1
predict.py --model_path ../trained_models/roberta_1_gectorv2finetuned.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/prediction_files/Linguaskill_test_FineTuned/roberta_ns.pred --transformer_model roberta --special_tokens_fix 1 --iteration_count 1 --speech 0
predict.py --model_path ../trained_models/best.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/prediction_files/Linguaskill_test_FineTuned/roberta.pred --transformer_model roberta --special_tokens_fix 1 --iteration_count 1 --speech 1
predict.py --model_path ../trained_models/roberta_1_gectorv2finetuned.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/prediction_files/Linguaskill_test_FineTuned/roberta.pred --transformer_model roberta --special_tokens_fix 1 --iteration_count 1 --speech 1
predict.py --model_path ../trained_models/bert_0_gectorv2finetuned.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/prediction_files/Linguaskill_test_FineTuned/bert.pred --transformer_model bert --special_tokens_fix 0 --iteration_count 1 --speech 1
predict.py --model_path ../trained_models/bert_0_gectorv2finetuned.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/prediction_files/Linguaskill_test_FineTuned/xlnet.pred --transformer_model xlnet --special_tokens_fix 0 --iteration_count 1 --speech 1
predict.py --model_path ../trained_models/xlnet_0_gectorv2finetuned.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/prediction_files/Linguaskill_test_FineTuned/xlnet.pred --transformer_model xlnet --special_tokens_fix 0 --iteration_count 1 --speech 1
predict.py --model_path ../trained_models/xlnet_0_gectorv2finetuned.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/prediction_files/Linguaskill_test_FineTuned/xlnet.pred --transformer_model xlnet --special_tokens_fix 0 --iteration_count 1 --speech 1
predict.py --model_path ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/prediction_files/Linguaskill_test_FineTuned/xlnet.pred --transformer_model xlnet --special_tokens_fix 0 --iteration_count 1 --speech 1 --is_ensemble 1
predict.py --model_path ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/prediction_files/Linguaskill_test_FineTuned/ensemble.pred --transformer_model xlnet --special_tokens_fix 0 --iteration_count 1 --speech 1 --is_ensemble 1
predict.py --model_path ../trained_models/xlnet_0_gectorv2finetuned.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/prediction_files/Linguaskill_test_FineTuned/xlnet.pred --transformer_model xlnet --special_tokens_fix 0 --iteration_count 1 --speech 1
predict.py --model_path ../trained_models/xlnet_0_gectorv2finetuned.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/prediction_files/Linguaskill_test_FineTuned/xlnet_ns.pred --transformer_model xlnet --special_tokens_fix 0 --iteration_count 1 --speech 0
predict.py --model_path ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/prediction_files/Linguaskill_test_FineTuned/ensemble_ns.pred --transformer_model xlnet --special_tokens_fix 0 --iteration_count 1 --speech 0 --is_ensemble 1
predict.py --model_path ../trained_models/bert_0_gectorv2finetuned.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/prediction_files/Linguaskill_test_FineTuned/bert_ns.pred --transformer_model bert --special_tokens_fix 0 --iteration_count 1 --speech 0
predict.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/prediction_files/Linguaskill_test/ensemble_ns.pred --transformer_model xlnet --special_tokens_fix 0 --iteration_count 1 --speech 0 --is_ensemble 1
predict.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/prediction_files/Linguaskill_test/ensemble_ns.pred --transformer_model xlnet --special_tokens_fix 0 --iteration_count 1 --speech 0 --is_ensemble 1
predict.py --model_path ../trained_models/bert_0_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/prediction_files/Linguaskill_test/bert_ns.pred --transformer_model bert --special_tokens_fix 0 --iteration_count 1 --speech 0
predict.py --model_path ../trained_models/xlnet_0_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/prediction_files/Linguaskill_test/xlnet_ns.pred --transformer_model xlnet --special_tokens_fix 0 --iteration_count 1 --speech 0
predict.py --model_path ../trained_models/roberta_0_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/prediction_files/Linguaskill_test/roberta_ns.pred --transformer_model roberta --special_tokens_fix 1 --iteration_count 1 --speech 0
predict.py --model_path ../trained_models/roberta_1_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/prediction_files/Linguaskill_test/roberta_ns.pred --transformer_model roberta --special_tokens_fix 1 --iteration_count 1 --speech 0

predict.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/prediction_files/Linguaskill_test/ensemble_whp.pred --transformer_model xlnet --special_tokens_fix 0 --is_ensemble 1 --iteration_count 1 --speech 1 --min_error_probability 0.40 --additional_confidence 0.16predict.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/prediction_files/Linguaskill_test/ensemble_whp.pred --transformer_model xlnet --special_tokens_fix 0 --is_ensemble 1 --iteration_count 1 --speech 1 --min_error_probability 0.40 --additional_confidence 0.16
predict.py --model_path ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/prediction_files/Linguaskill_test_ft/ensemble_whp.pred --transformer_model xlnet --special_tokens_fix 0 --is_ensemble 1 --iteration_count 1 --speech 1 --min_error_probability 0.40 --additional_confidence 0.16
predict.py --model_path ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/prediction_files/Linguaskill_test_FineTuned/ensemble_whp.pred --transformer_model xlnet --special_tokens_fix 0 --is_ensemble 1 --iteration_count 1 --speech 1 --min_error_probability 0.40 --additional_confidence 0.16
predict.py --model_path ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/FCE/fce-public.test.inc --output_file experiments/prediction_files/FCE/ensemble_whp.pred --transformer_model xlnet --special_tokens_fix 0 --is_ensemble 1 --iteration_count 1 --speech 1 --min_error_probability 0.40 --additional_confidence 0.16
predict.py --model_path ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/prediction_files/Linguaskill_combi/ensemble_whp.pred --transformer_model xlnet --special_tokens_fix 0 --is_ensemble 1 --iteration_count 1 --speech 1 --min_error_probability 0.40 --additional_confidence 0.16
predict.py --model_path ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/prediction_files/Linguaskill_combi/ensemble.pred --transformer_model xlnet --special_tokens_fix 0 --is_ensemble 1 --iteration_count 1 --speech 1
predict.py --model_path ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/prediction_files/Linguaskill_combi/ensemble.pred --transformer_model xlnet --special_tokens_fix 0 --is_ensemble 1 --iteration_count 1 --speech 1
predict.py --model_path ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --output_file experiments/prediction_files/Linguaskill_combi/ensemble.pred --transformer_model xlnet --special_tokens_fix 0 --is_ensemble 1 --iteration_count 1 --speech 1
predict.py --model_path ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed_whisperflt/ls_test.inc --output_file experiments/prediction_files/Linguaskill_whisperflt/ensemble_all.pred --transformer_model xlnet --special_tokens_fix 0 --is_ensemble 1 --iteration_count 1 --speech 1predict.py --model_path ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed_whisperflt/ls_test.inc --output_file experiments/prediction_files/Linguaskill_whisperflt/ensemble_all.pred --transformer_model xlnet --special_tokens_fix 0 --is_ensemble 1 --iteration_count 1 --speech 1
predict.py --model_path ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed_whisperflt/ls_test.inc --output_file experiments/prediction_files/Linguaskill_whisperflt/ensemble_all.pred --transformer_model xlnet --special_tokens_fix 0 --is_ensemble 1 --iteration_count 1
predict.py --model_path ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed_whisperflt/ls_test.inc --output_file experiments/prediction_files/Linguaskill_whisperflt/ensemble_all.pred --transformer_model xlnet --special_tokens_fix 0 --is_ensemble 1 --iteration_count 1
predict.py --model_path ../trained_models/xlnet_0_gectorv2finetuned.th ../trained_models/bert_0_gectorv2finetuned.th ../trained_models/roberta_1_gectorv2finetuned.th ../trained_models/xlnet_0_gectorv2.th ../trained_models/bert_0_gectorv2.th ../trained_models/roberta_1_gectorv2.th --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed_whisperflt/ls_test.inc --output_file experiments/prediction_files/Linguaskill_whisperflt/ensemble_all.pred --transformer_model xlnet --special_tokens_fix 0 --is_ensemble 1 --iteration_count 1 --speech 1
