uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/FCE/fce-public.test.inc --target_file ../data/FCE/fce-public.test.corr
uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/FCE/fce-public.test.inc --target_file ../data/FCE/fce-public.test.corr
uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --target_file ../data/Linguaskill/preprocessed/ls_test.corr
uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/FCE/fce-public.test.inc --target_file ../data/FCE/fce-public.test.corr
uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --target_file ../data/Linguaskill/preprocessed/ls_test.corr
uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --target_file ../data/Linguaskill/preprocessed/ls_test.corr --method 2
uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --target_file ../data/Linguaskill/preprocessed/ls_test.corr --method 2
uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --target_file ../data/Linguaskill/preprocessed/ls_test.corr --method 2
uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --target_file ../data/Linguaskill/preprocessed/ls_test.corr --method 2
uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --target_file ../data/Linguaskill/preprocessed/ls_test.corr --method 2
uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --target_file ../data/Linguaskill/preprocessed/ls_test.corr --method 2
uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --target_file ../data/Linguaskill/preprocessed/ls_test.corr --method 2
uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --target_file ../data/Linguaskill/preprocessed/ls_test.corr --method 1
uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --target_file ../data/Linguaskill/preprocessed/ls_test.corr --method 1
uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --target_file ../data/Linguaskill/preprocessed/ls_test.corr --method 1
uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --target_file ../data/Linguaskill/preprocessed/ls_test.corr --method 1
uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --target_file ../data/Linguaskill/preprocessed/ls_test.corr --method 1
uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --target_file ../data/Linguaskill/preprocessed/ls_test.corr --method 1
uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --target_file ../data/Linguaskill/preprocessed/ls_test.corr --method 1
uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/FCE/fce-public.test.inc --target_file ../data/FCE/fce-public.test.corr --method 1
uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/FCE/fce-public.test.inc --target_file ../data/FCE/fce-public.test.corr --method 2
uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/FCE/fce-public.test.inc --target_file ../data/FCE/fce-public.test.corr --method 2
uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/FCE/fce-public.test.inc --target_file ../data/FCE/fce-public.test.corr --method 2
uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/FCE/fce-public.test.inc --target_file ../data/FCE/fce-public.test.corr --method 2
uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/FCE/fce-public.test.inc --target_file ../data/FCE/fce-public.test.corr --method 2
uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/FCE/fce-public.test.inc --target_file ../data/FCE/fce-public.test.corr --method 2
uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/FCE/fce-public.test.inc --target_file ../data/FCE/fce-public.test.corr --method 2
uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/FCE/fce-public.test.inc --target_file ../data/FCE/fce-public.test.corr --method 2
uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/FCE/fce-public.test.inc --target_file ../data/FCE/fce-public.test.corr --method 2
uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/FCE/fce-public.test.inc --target_file ../data/FCE/fce-public.test.corr --method 2
uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/FCE/fce-public.test.inc --target_file ../data/FCE/fce-public.test.corr --method 2
uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/FCE/fce-public.test.inc --target_file ../data/FCE/fce-public.test.corr --method 2
uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/FCE/fce-public.test.inc --target_file ../data/FCE/fce-public.test.corr --method 2
uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/FCE/fce-public.test.inc --target_file ../data/FCE/fce-public.test.corr --method 2
uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --target_file ../data/Linguaskill/preprocessed/ls_test.corr --method 2
uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --target_file ../data/Linguaskill/preprocessed/ls_test.corr --output_dir experiments/pr_data/uncertainty/Linguaskill_test --method 1 --speech 1
pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --target_file ../data/Linguaskill/preprocessed/ls_test.corr --output_dir experiments/pr_data/uncertainty/Linguaskill_test --method 1 --speech 1
pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --target_file ../data/Linguaskill/preprocessed/ls_test.corr --output_dir experiments/pr_data/uncertainty/Linguaskill_test --method 1 --speech 1
pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test_reduced.inc --target_file ../data/Linguaskill/preprocessed/ls_test_reduced.corr --output_dir experiments/pr_data/uncertainty/Linguaskill_test --method 1 --speech 1
pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test_reduced.inc --target_file ../data/Linguaskill/preprocessed/ls_test_reduced.corr --output_dir experiments/pr_data/uncertainty/Linguaskill_test --method 1 --speech 1
pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test_reduced.inc --target_file ../data/Linguaskill/preprocessed/ls_test_reduced.corr --output_dir experiments/pr_data/uncertainty/Linguaskill_test --method 1 --speech 1
pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test_reduced.inc --target_file ../data/Linguaskill/preprocessed/ls_test_reduced.corr --output_dir experiments/pr_data/uncertainty/Linguaskill_test --method 1 --speech 1
pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test_reduced.inc --target_file ../data/Linguaskill/preprocessed/ls_test_reduced.corr --output_dir experiments/pr_data/uncertainty/Linguaskill_test --method 1 --speech 1 --n_steps 10
pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test_reduced.inc --target_file ../data/Linguaskill/preprocessed/ls_test_reduced.corr --output_dir experiments/pr_data/uncertainty/Linguaskill_test --method 1 --speech 1 --n_steps 10
pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test_reduced.inc --target_file ../data/Linguaskill/preprocessed/ls_test_reduced.corr --output_dir experiments/pr_data/uncertainty/Linguaskill_test --method 1 --speech 1 --n_steps 10
pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test_reduced.inc --target_file ../data/Linguaskill/preprocessed/ls_test_reduced.corr --output_dir experiments/pr_data/uncertainty/Linguaskill_test --method 1 --speech 1 --n_steps 10
pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test_reduced.inc --target_file ../data/Linguaskill/preprocessed/ls_test_reduced.corr --output_dir experiments/pr_data/uncertainty/Linguaskill_test --method 1 --speech 1 --n_steps 10
pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test_reduced.inc --target_file ../data/Linguaskill/preprocessed/ls_test_reduced.corr --output_dir experiments/pr_data/uncertainty/Linguaskill_test --method 1 --speech 1 --n_steps 10
pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test_reduced.inc --target_file ../data/Linguaskill/preprocessed/ls_test_reduced.corr --output_dir experiments/pr_data/uncertainty/Linguaskill_test --method 1 --speech 1 --n_steps 10
pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test_reduced.inc --target_file ../data/Linguaskill/preprocessed/ls_test_reduced.corr --output_dir experiments/pr_data/uncertainty/Linguaskill_test --method 1 --speech 1 --n_steps 10
pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test_reduced.inc --target_file ../data/Linguaskill/preprocessed/ls_test_reduced.corr --output_dir experiments/pr_data/uncertainty/Linguaskill_test --method 1 --speech 1 --n_steps 10
pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test_reduced.inc --target_file ../data/Linguaskill/preprocessed/ls_test_reduced.corr --output_dir experiments/pr_data/uncertainty/Linguaskill_test --method 1 --speech 1 --n_steps 10
pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test_reduced.inc --target_file ../data/Linguaskill/preprocessed/ls_test_reduced.corr --output_dir experiments/pr_data/uncertainty/Linguaskill_test --method 1 --speech 1 --n_steps 10
pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test_reduced.inc --target_file ../data/Linguaskill/preprocessed/ls_test_reduced.corr --output_dir experiments/pr_data/uncertainty/Linguaskill_test --method 1 --speech 1 --n_steps 3
pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test_reduced.inc --target_file ../data/Linguaskill/preprocessed/ls_test_reduced.corr --output_dir experiments/pr_data/uncertainty/Linguaskill_test --method 1 --speech 1 --n_steps 2
pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test_reduced.inc --target_file ../data/Linguaskill/preprocessed/ls_test_reduced.corr --output_dir experiments/pr_data/uncertainty/Linguaskill_test --method 1 --speech 1 --n_steps 2
pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test_reduced.inc --target_file ../data/Linguaskill/preprocessed/ls_test_reduced.corr --output_dir experiments/pr_data/uncertainty/Linguaskill_test --method 1 --speech 1 --n_steps 2
pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test_reduced.inc --target_file ../data/Linguaskill/preprocessed/ls_test_reduced.corr --output_dir experiments/pr_data/uncertainty/Linguaskill_test --method 1 --speech 1 --n_steps 2
pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test_reduced.inc --target_file ../data/Linguaskill/preprocessed/ls_test_reduced.corr --output_dir experiments/pr_data/uncertainty/Linguaskill_test --method 1 --speech 1 --n_steps 2
pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test_reduced.inc --target_file ../data/Linguaskill/preprocessed/ls_test_reduced.corr --output_dir experiments/pr_data/uncertainty/Linguaskill_test --method 1 --speech 1 --n_steps 2
pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test_reduced.inc --target_file ../data/Linguaskill/preprocessed/ls_test_reduced.corr --output_dir experiments/pr_data/uncertainty/Linguaskill_test --method 1 --speech 1 --n_steps 10
pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --target_file ../data/Linguaskill/preprocessed/ls_test.corr --output_dir experiments/pr_data/uncertainty/Linguaskill_test --method 1 --speech 1 --n_steps 200
pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/FCE/fce-public.test.inc --target_file ../data/FCE/fce-public.test.corr --output_dir experiments/pr_data/uncertainty/FCE --method 1 --speech 1 --n_steps 200pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --target_file ../data/Linguaskill/preprocessed/ls_test.corr --output_dir experiments/pr_data/uncertainty/Linguaskill_test --method 1 --speech 1 --n_steps 200
pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/FCE/fce-public.test.inc --target_file ../data/FCE/fce-public.test.corr --output_dir experiments/pr_data/uncertainty/FCE --method 1 --speech 1 --n_steps 200
pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/FCE/fce-public.test.inc --target_file ../data/FCE/fce-public.test.corr --output_dir experiments/pr_data/uncertainty/FCE --method 1 --speech 0 --n_steps 200
pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test_reduced.inc --target_file ../data/Linguaskill/preprocessed/ls_test_reduced.corr --output_dir experiments/pr_data/uncertainty/Linguaskill_test_red --method 1 --speech 1 --n_steps 10
pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test_reduced.inc --target_file ../data/Linguaskill/preprocessed/ls_test_reduced.corr --output_dir experiments/pr_data/uncertainty/Linguaskill_test_red --method 1 --speech 1 --n_steps 10
pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test_reduced.inc --target_file ../data/Linguaskill/preprocessed/ls_test_reduced.corr --output_dir experiments/pr_data/uncertainty/Linguaskill_test_red --method 1 --speech 1 --n_steps 10
pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/FCE/fce-public.test.inc --target_file ../data/FCE/fce-public.test.corr --output_dir experiments/pr_data/uncertainty/FCE --method 1 --speech 0 --n_steps 200
pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --target_file ../data/Linguaskill/preprocessed/ls_test.corr --output_dir experiments/pr_data/uncertainty/Linguaskill_test_ft --method 1 --speech 1 --n_steps 200 --finetuned 1
pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --target_file ../data/Linguaskill/preprocessed/ls_test.corr --output_dir experiments/pr_data/uncertainty/Linguaskill_test --method 1 --speech 1 --n_steps 200 --finetuned 0
pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --target_file ../data/Linguaskill/preprocessed/ls_test.corr --output_dir experiments/pr_data/uncertainty/Linguaskill_test_ft --method 1 --speech 1 --n_steps 200 --finetuned 1
pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --target_file ../data/Linguaskill/preprocessed/ls_test.corr --output_dir experiments/pr_data/uncertainty/Linguaskill_test_ft --method 1 --speech 1 --n_steps 200 --finetuned 1
pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --target_file ../data/Linguaskill/preprocessed/ls_test.corr --output_dir experiments/pr_data/uncertainty/Linguaskill_test_ft --method 1 --speech 1 --n_steps 200 --finetuned 1
pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --target_file ../data/Linguaskill/preprocessed/ls_test.corr --output_dir experiments/pr_data/uncertainty/Linguaskill_test_ft --method 1 --speech 1 --n_steps 200 --finetuned 1
pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --target_file ../data/Linguaskill/preprocessed/ls_test.corr --output_dir experiments/pr_data/uncertainty/Linguaskill_test --method 1 --speech 1 --n_steps 75 --finetuned 0
pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --target_file ../data/Linguaskill/preprocessed/ls_test.corr --output_dir experiments/pr_data/uncertainty/Linguaskill_test --method 1 --speech 1 --n_steps 75 --finetuned 0
pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test_reduced.inc --target_file ../data/Linguaskill/preprocessed/ls_test_reduced.corr --output_dir experiments/pr_data/uncertainty/Linguaskill_test_red --method 1 --speech 1 --n_steps 75 --finetuned 1 --combined 1
pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test_reduced.inc --target_file ../data/Linguaskill/preprocessed/ls_test_reduced.corr --output_dir experiments/pr_data/uncertainty/Linguaskill_test_red --method 1 --speech 1 --n_steps 75 --finetuned 1 --combined 1
pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test_reduced.inc --target_file ../data/Linguaskill/preprocessed/ls_test_reduced.corr --output_dir experiments/pr_data/uncertainty/Linguaskill_test_red --method 1 --speech 1 --n_steps 75 --finetuned 1 --combined 1
pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test_reduced.inc --target_file ../data/Linguaskill/preprocessed/ls_test_reduced.corr --output_dir experiments/pr_data/uncertainty/Linguaskill_test_red --method 1 --speech 1 --n_steps 75 --finetuned 1 --combined 1
pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test_reduced.inc --target_file ../data/Linguaskill/preprocessed/ls_test_reduced.corr --output_dir experiments/pr_data/uncertainty/Linguaskill_test_red --method 1 --speech 1 --n_steps 75 --finetuned 1 --combined 1
pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test_reduced.inc --target_file ../data/Linguaskill/preprocessed/ls_test_reduced.corr --output_dir experiments/pr_data/uncertainty/Linguaskill_test_red --method 1 --speech 1 --n_steps 75 --finetuned 1
pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test_reduced.inc --target_file ../data/Linguaskill/preprocessed/ls_test_reduced.corr --output_dir experiments/pr_data/uncertainty/Linguaskill_test_red --method 1 --speech 1 --n_steps 75 --finetuned 1
pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test_reduced.inc --target_file ../data/Linguaskill/preprocessed/ls_test_reduced.corr --output_dir experiments/pr_data/uncertainty/Linguaskill_test_red --method 1 --speech 1 --n_steps 75 --finetuned 1
pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test_reduced.inc --target_file ../data/Linguaskill/preprocessed/ls_test_reduced.corr --output_dir experiments/pr_data/uncertainty/Linguaskill_test_red --method 1 --speech 1 --n_steps 75 --finetuned 1 --combined 1
pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --target_file ../data/Linguaskill/preprocessed/ls_test.corr --output_dir experiments/pr_data/uncertainty/Linguaskill_test_comb --method 1 --speech 1 --n_steps 100 --finetuned 1 --combined 1
pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --target_file ../data/Linguaskill/preprocessed/ls_test.corr --output_dir experiments/pr_data/uncertainty/Linguaskill_test_comb --method 1 --speech 1 --n_steps 75 --finetuned 1 --combined 1
pr_uncertainty.py --vocab_path data/output_vocabulary --input_file ../data/Linguaskill/preprocessed/ls_test.inc --target_file ../data/Linguaskill/preprocessed/ls_test.corr --output_dir experiments/pr_data/uncertainty/Linguaskill_combi --method 1 --speech 1 --n_steps 50 --finetuned 1 --combined 1
